/*
* generated by Xtext
*/
package net.sf.fmurf.ui.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class FmurfUiDSLProposalProvider extends AbstractFmurfUiDSLProposalProvider {

}
