/*
* generated by Xtext
*/
package net.sf.fmurf.ui.parseTreeConstruction;

import net.sf.fmurf.ui.services.FmurfUiDSLGrammarAccess;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.parsetree.reconstr.IEObjectConsumer;
import org.eclipse.xtext.parsetree.reconstr.impl.AbstractParseTreeConstructor;

import com.google.inject.Inject;

@SuppressWarnings("all")
public class FmurfUiDSLParsetreeConstructor extends AbstractParseTreeConstructor {
		
	@Inject
	private FmurfUiDSLGrammarAccess grammarAccess;
	
	@Override
	protected AbstractToken getRootToken(IEObjectConsumer inst) {
		return new ThisRootNode(inst);	
	}
	
protected class ThisRootNode extends RootToken {
	public ThisRootNode(IEObjectConsumer inst) {
		super(inst);
	}
	
	@Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FMFUI_Group(this, this, 0, inst);
			case 1: return new Fiducial_Group(this, this, 1, inst);
			case 2: return new FMFSettings_Group(this, this, 2, inst);
			default: return null;
		}	
	}	
}
	

/************ begin Rule FMFUI ****************
 *
 * FMFUI:
 * 	settings=FMFSettings fiducials+=Fiducial*;
 *
 **/

// settings=FMFSettings fiducials+=Fiducial*
protected class FMFUI_Group extends GroupToken {
	
	public FMFUI_Group(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Group getGrammarElement() {
		return grammarAccess.getFMFUIAccess().getGroup();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FMFUI_FiducialsAssignment_1(lastRuleCallOrigin, this, 0, inst);
			case 1: return new FMFUI_SettingsAssignment_0(lastRuleCallOrigin, this, 1, inst);
			default: return null;
		}	
	}

    @Override
	public IEObjectConsumer tryConsume() {
		if(getEObject().eClass() != grammarAccess.getFMFUIRule().getType().getClassifier())
			return null;
		return eObjectConsumer;
	}

}

// settings=FMFSettings
protected class FMFUI_SettingsAssignment_0 extends AssignmentToken  {
	
	public FMFUI_SettingsAssignment_0(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFMFUIAccess().getSettingsAssignment_0();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FMFSettings_Group(this, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("settings",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("settings");
		if(value instanceof EObject) { // org::eclipse::xtext::impl::RuleCallImpl
			IEObjectConsumer param = createEObjectConsumer((EObject)value);
			if(param.isInstanceOf(grammarAccess.getFMFSettingsRule().getType().getClassifier())) {
				type = AssignmentType.PARSER_RULE_CALL;
				element = grammarAccess.getFMFUIAccess().getSettingsFMFSettingsParserRuleCall_0_0(); 
				consumed = obj;
				return param;
			}
		}
		return null;
	}

    @Override
	public AbstractToken createFollowerAfterReturn(AbstractToken next,	int actIndex, int index, IEObjectConsumer inst) {
		if(value == inst.getEObject() && !inst.isConsumed()) return null;
		switch(index) {
			default: return lastRuleCallOrigin.createFollowerAfterReturn(next, actIndex , index, consumed);
		}	
	}	
}

// fiducials+=Fiducial*
protected class FMFUI_FiducialsAssignment_1 extends AssignmentToken  {
	
	public FMFUI_FiducialsAssignment_1(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFMFUIAccess().getFiducialsAssignment_1();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_Group(this, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("fiducials",false)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("fiducials");
		if(value instanceof EObject) { // org::eclipse::xtext::impl::RuleCallImpl
			IEObjectConsumer param = createEObjectConsumer((EObject)value);
			if(param.isInstanceOf(grammarAccess.getFiducialRule().getType().getClassifier())) {
				type = AssignmentType.PARSER_RULE_CALL;
				element = grammarAccess.getFMFUIAccess().getFiducialsFiducialParserRuleCall_1_0(); 
				consumed = obj;
				return param;
			}
		}
		return null;
	}

    @Override
	public AbstractToken createFollowerAfterReturn(AbstractToken next,	int actIndex, int index, IEObjectConsumer inst) {
		if(value == inst.getEObject() && !inst.isConsumed()) return null;
		switch(index) {
			case 0: return new FMFUI_FiducialsAssignment_1(lastRuleCallOrigin, next, actIndex, consumed);
			case 1: return new FMFUI_SettingsAssignment_0(lastRuleCallOrigin, next, actIndex, consumed);
			default: return null;
		}	
	}	
}


/************ end Rule FMFUI ****************/


/************ begin Rule Fiducial ****************
 *
 * Fiducial:
 * 	"fiducial" name=ID ":" uid=INT "{" "style:" style=FMFFidStyleEnum "kind:" kind=FMFKind "foreground:"
 * 	fg=FMFFidColorEnum "background:" bg=FMFFidColorEnum "radius:" radius=INT "proxima:" proxima=INT "proximaVisible:"
 * 	proximaVisible=FMFProximaVisibleEnum "function:" function=FMFFidFunctionEnum "range:" range=INT "}";
 *
 **/

// "fiducial" name=ID ":" uid=INT "{" "style:" style=FMFFidStyleEnum "kind:" kind=FMFKind "foreground:" fg=FMFFidColorEnum
// "background:" bg=FMFFidColorEnum "radius:" radius=INT "proxima:" proxima=INT "proximaVisible:"
// proximaVisible=FMFProximaVisibleEnum "function:" function=FMFFidFunctionEnum "range:" range=INT "}"
protected class Fiducial_Group extends GroupToken {
	
	public Fiducial_Group(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Group getGrammarElement() {
		return grammarAccess.getFiducialAccess().getGroup();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_RightCurlyBracketKeyword_23(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override
	public IEObjectConsumer tryConsume() {
		if(getEObject().eClass() != grammarAccess.getFiducialRule().getType().getClassifier())
			return null;
		return eObjectConsumer;
	}

}

// "fiducial"
protected class Fiducial_FiducialKeyword_0 extends KeywordToken  {
	
	public Fiducial_FiducialKeyword_0(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFiducialAccess().getFiducialKeyword_0();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			default: return lastRuleCallOrigin.createFollowerAfterReturn(this, index, index, inst);
		}	
	}

}

// name=ID
protected class Fiducial_NameAssignment_1 extends AssignmentToken  {
	
	public Fiducial_NameAssignment_1(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFiducialAccess().getNameAssignment_1();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_FiducialKeyword_0(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("name",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("name");
		if(valueSerializer.isValid(obj.getEObject(), grammarAccess.getFiducialAccess().getNameIDTerminalRuleCall_1_0(), value, null)) {
			type = AssignmentType.TERMINAL_RULE_CALL;
			element = grammarAccess.getFiducialAccess().getNameIDTerminalRuleCall_1_0();
			return obj;
		}
		return null;
	}

}

// ":"
protected class Fiducial_ColonKeyword_2 extends KeywordToken  {
	
	public Fiducial_ColonKeyword_2(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFiducialAccess().getColonKeyword_2();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_NameAssignment_1(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// uid=INT
protected class Fiducial_UidAssignment_3 extends AssignmentToken  {
	
	public Fiducial_UidAssignment_3(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFiducialAccess().getUidAssignment_3();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_ColonKeyword_2(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("uid",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("uid");
		if(valueSerializer.isValid(obj.getEObject(), grammarAccess.getFiducialAccess().getUidINTTerminalRuleCall_3_0(), value, null)) {
			type = AssignmentType.TERMINAL_RULE_CALL;
			element = grammarAccess.getFiducialAccess().getUidINTTerminalRuleCall_3_0();
			return obj;
		}
		return null;
	}

}

// "{"
protected class Fiducial_LeftCurlyBracketKeyword_4 extends KeywordToken  {
	
	public Fiducial_LeftCurlyBracketKeyword_4(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFiducialAccess().getLeftCurlyBracketKeyword_4();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_UidAssignment_3(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// "style:"
protected class Fiducial_StyleKeyword_5 extends KeywordToken  {
	
	public Fiducial_StyleKeyword_5(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFiducialAccess().getStyleKeyword_5();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_LeftCurlyBracketKeyword_4(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// style=FMFFidStyleEnum
protected class Fiducial_StyleAssignment_6 extends AssignmentToken  {
	
	public Fiducial_StyleAssignment_6(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFiducialAccess().getStyleAssignment_6();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_StyleKeyword_5(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("style",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("style");
		if(enumLitSerializer.isValid(obj.getEObject(), grammarAccess.getFiducialAccess().getStyleFMFFidStyleEnumEnumRuleCall_6_0(), value, null)) { 
			type = AssignmentType.ENUM_RULE_CALL;
			element = grammarAccess.getFiducialAccess().getStyleFMFFidStyleEnumEnumRuleCall_6_0();
			return obj;
		}
		return null;
	}

}

// "kind:"
protected class Fiducial_KindKeyword_7 extends KeywordToken  {
	
	public Fiducial_KindKeyword_7(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFiducialAccess().getKindKeyword_7();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_StyleAssignment_6(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// kind=FMFKind
protected class Fiducial_KindAssignment_8 extends AssignmentToken  {
	
	public Fiducial_KindAssignment_8(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFiducialAccess().getKindAssignment_8();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_KindKeyword_7(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("kind",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("kind");
		if(enumLitSerializer.isValid(obj.getEObject(), grammarAccess.getFiducialAccess().getKindFMFKindEnumRuleCall_8_0(), value, null)) { 
			type = AssignmentType.ENUM_RULE_CALL;
			element = grammarAccess.getFiducialAccess().getKindFMFKindEnumRuleCall_8_0();
			return obj;
		}
		return null;
	}

}

// "foreground:"
protected class Fiducial_ForegroundKeyword_9 extends KeywordToken  {
	
	public Fiducial_ForegroundKeyword_9(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFiducialAccess().getForegroundKeyword_9();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_KindAssignment_8(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// fg=FMFFidColorEnum
protected class Fiducial_FgAssignment_10 extends AssignmentToken  {
	
	public Fiducial_FgAssignment_10(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFiducialAccess().getFgAssignment_10();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_ForegroundKeyword_9(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("fg",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("fg");
		if(enumLitSerializer.isValid(obj.getEObject(), grammarAccess.getFiducialAccess().getFgFMFFidColorEnumEnumRuleCall_10_0(), value, null)) { 
			type = AssignmentType.ENUM_RULE_CALL;
			element = grammarAccess.getFiducialAccess().getFgFMFFidColorEnumEnumRuleCall_10_0();
			return obj;
		}
		return null;
	}

}

// "background:"
protected class Fiducial_BackgroundKeyword_11 extends KeywordToken  {
	
	public Fiducial_BackgroundKeyword_11(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFiducialAccess().getBackgroundKeyword_11();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_FgAssignment_10(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// bg=FMFFidColorEnum
protected class Fiducial_BgAssignment_12 extends AssignmentToken  {
	
	public Fiducial_BgAssignment_12(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFiducialAccess().getBgAssignment_12();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_BackgroundKeyword_11(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("bg",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("bg");
		if(enumLitSerializer.isValid(obj.getEObject(), grammarAccess.getFiducialAccess().getBgFMFFidColorEnumEnumRuleCall_12_0(), value, null)) { 
			type = AssignmentType.ENUM_RULE_CALL;
			element = grammarAccess.getFiducialAccess().getBgFMFFidColorEnumEnumRuleCall_12_0();
			return obj;
		}
		return null;
	}

}

// "radius:"
protected class Fiducial_RadiusKeyword_13 extends KeywordToken  {
	
	public Fiducial_RadiusKeyword_13(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFiducialAccess().getRadiusKeyword_13();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_BgAssignment_12(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// radius=INT
protected class Fiducial_RadiusAssignment_14 extends AssignmentToken  {
	
	public Fiducial_RadiusAssignment_14(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFiducialAccess().getRadiusAssignment_14();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_RadiusKeyword_13(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("radius",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("radius");
		if(valueSerializer.isValid(obj.getEObject(), grammarAccess.getFiducialAccess().getRadiusINTTerminalRuleCall_14_0(), value, null)) {
			type = AssignmentType.TERMINAL_RULE_CALL;
			element = grammarAccess.getFiducialAccess().getRadiusINTTerminalRuleCall_14_0();
			return obj;
		}
		return null;
	}

}

// "proxima:"
protected class Fiducial_ProximaKeyword_15 extends KeywordToken  {
	
	public Fiducial_ProximaKeyword_15(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFiducialAccess().getProximaKeyword_15();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_RadiusAssignment_14(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// proxima=INT
protected class Fiducial_ProximaAssignment_16 extends AssignmentToken  {
	
	public Fiducial_ProximaAssignment_16(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFiducialAccess().getProximaAssignment_16();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_ProximaKeyword_15(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("proxima",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("proxima");
		if(valueSerializer.isValid(obj.getEObject(), grammarAccess.getFiducialAccess().getProximaINTTerminalRuleCall_16_0(), value, null)) {
			type = AssignmentType.TERMINAL_RULE_CALL;
			element = grammarAccess.getFiducialAccess().getProximaINTTerminalRuleCall_16_0();
			return obj;
		}
		return null;
	}

}

// "proximaVisible:"
protected class Fiducial_ProximaVisibleKeyword_17 extends KeywordToken  {
	
	public Fiducial_ProximaVisibleKeyword_17(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFiducialAccess().getProximaVisibleKeyword_17();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_ProximaAssignment_16(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// proximaVisible=FMFProximaVisibleEnum
protected class Fiducial_ProximaVisibleAssignment_18 extends AssignmentToken  {
	
	public Fiducial_ProximaVisibleAssignment_18(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFiducialAccess().getProximaVisibleAssignment_18();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_ProximaVisibleKeyword_17(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("proximaVisible",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("proximaVisible");
		if(enumLitSerializer.isValid(obj.getEObject(), grammarAccess.getFiducialAccess().getProximaVisibleFMFProximaVisibleEnumEnumRuleCall_18_0(), value, null)) { 
			type = AssignmentType.ENUM_RULE_CALL;
			element = grammarAccess.getFiducialAccess().getProximaVisibleFMFProximaVisibleEnumEnumRuleCall_18_0();
			return obj;
		}
		return null;
	}

}

// "function:"
protected class Fiducial_FunctionKeyword_19 extends KeywordToken  {
	
	public Fiducial_FunctionKeyword_19(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFiducialAccess().getFunctionKeyword_19();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_ProximaVisibleAssignment_18(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// function=FMFFidFunctionEnum
protected class Fiducial_FunctionAssignment_20 extends AssignmentToken  {
	
	public Fiducial_FunctionAssignment_20(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFiducialAccess().getFunctionAssignment_20();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_FunctionKeyword_19(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("function",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("function");
		if(enumLitSerializer.isValid(obj.getEObject(), grammarAccess.getFiducialAccess().getFunctionFMFFidFunctionEnumEnumRuleCall_20_0(), value, null)) { 
			type = AssignmentType.ENUM_RULE_CALL;
			element = grammarAccess.getFiducialAccess().getFunctionFMFFidFunctionEnumEnumRuleCall_20_0();
			return obj;
		}
		return null;
	}

}

// "range:"
protected class Fiducial_RangeKeyword_21 extends KeywordToken  {
	
	public Fiducial_RangeKeyword_21(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFiducialAccess().getRangeKeyword_21();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_FunctionAssignment_20(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// range=INT
protected class Fiducial_RangeAssignment_22 extends AssignmentToken  {
	
	public Fiducial_RangeAssignment_22(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFiducialAccess().getRangeAssignment_22();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_RangeKeyword_21(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("range",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("range");
		if(valueSerializer.isValid(obj.getEObject(), grammarAccess.getFiducialAccess().getRangeINTTerminalRuleCall_22_0(), value, null)) {
			type = AssignmentType.TERMINAL_RULE_CALL;
			element = grammarAccess.getFiducialAccess().getRangeINTTerminalRuleCall_22_0();
			return obj;
		}
		return null;
	}

}

// "}"
protected class Fiducial_RightCurlyBracketKeyword_23 extends KeywordToken  {
	
	public Fiducial_RightCurlyBracketKeyword_23(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFiducialAccess().getRightCurlyBracketKeyword_23();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Fiducial_RangeAssignment_22(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}


/************ end Rule Fiducial ****************/


/************ begin Rule FMFSettings ****************
 *
 * FMFSettings:
 * 	"settings : {" "OscReceivePort:" oscReceivePort=INT "OscSendAddress:" oscSendAddress=STRING "OscSendPort:"
 * 	oscSendPort=INT "TuioPort:" tuioPort=INT "liveRate:" liveRate=INT "processingRate:" processingRate=INT "}";
 *
 **/

// "settings : {" "OscReceivePort:" oscReceivePort=INT "OscSendAddress:" oscSendAddress=STRING "OscSendPort:"
// oscSendPort=INT "TuioPort:" tuioPort=INT "liveRate:" liveRate=INT "processingRate:" processingRate=INT "}"
protected class FMFSettings_Group extends GroupToken {
	
	public FMFSettings_Group(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Group getGrammarElement() {
		return grammarAccess.getFMFSettingsAccess().getGroup();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FMFSettings_RightCurlyBracketKeyword_13(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override
	public IEObjectConsumer tryConsume() {
		if(getEObject().eClass() != grammarAccess.getFMFSettingsRule().getType().getClassifier())
			return null;
		return eObjectConsumer;
	}

}

// "settings : {"
protected class FMFSettings_SettingsKeyword_0 extends KeywordToken  {
	
	public FMFSettings_SettingsKeyword_0(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFMFSettingsAccess().getSettingsKeyword_0();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			default: return lastRuleCallOrigin.createFollowerAfterReturn(this, index, index, inst);
		}	
	}

}

// "OscReceivePort:"
protected class FMFSettings_OscReceivePortKeyword_1 extends KeywordToken  {
	
	public FMFSettings_OscReceivePortKeyword_1(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFMFSettingsAccess().getOscReceivePortKeyword_1();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FMFSettings_SettingsKeyword_0(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// oscReceivePort=INT
protected class FMFSettings_OscReceivePortAssignment_2 extends AssignmentToken  {
	
	public FMFSettings_OscReceivePortAssignment_2(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFMFSettingsAccess().getOscReceivePortAssignment_2();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FMFSettings_OscReceivePortKeyword_1(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("oscReceivePort",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("oscReceivePort");
		if(valueSerializer.isValid(obj.getEObject(), grammarAccess.getFMFSettingsAccess().getOscReceivePortINTTerminalRuleCall_2_0(), value, null)) {
			type = AssignmentType.TERMINAL_RULE_CALL;
			element = grammarAccess.getFMFSettingsAccess().getOscReceivePortINTTerminalRuleCall_2_0();
			return obj;
		}
		return null;
	}

}

// "OscSendAddress:"
protected class FMFSettings_OscSendAddressKeyword_3 extends KeywordToken  {
	
	public FMFSettings_OscSendAddressKeyword_3(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFMFSettingsAccess().getOscSendAddressKeyword_3();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FMFSettings_OscReceivePortAssignment_2(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// oscSendAddress=STRING
protected class FMFSettings_OscSendAddressAssignment_4 extends AssignmentToken  {
	
	public FMFSettings_OscSendAddressAssignment_4(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFMFSettingsAccess().getOscSendAddressAssignment_4();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FMFSettings_OscSendAddressKeyword_3(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("oscSendAddress",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("oscSendAddress");
		if(valueSerializer.isValid(obj.getEObject(), grammarAccess.getFMFSettingsAccess().getOscSendAddressSTRINGTerminalRuleCall_4_0(), value, null)) {
			type = AssignmentType.TERMINAL_RULE_CALL;
			element = grammarAccess.getFMFSettingsAccess().getOscSendAddressSTRINGTerminalRuleCall_4_0();
			return obj;
		}
		return null;
	}

}

// "OscSendPort:"
protected class FMFSettings_OscSendPortKeyword_5 extends KeywordToken  {
	
	public FMFSettings_OscSendPortKeyword_5(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFMFSettingsAccess().getOscSendPortKeyword_5();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FMFSettings_OscSendAddressAssignment_4(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// oscSendPort=INT
protected class FMFSettings_OscSendPortAssignment_6 extends AssignmentToken  {
	
	public FMFSettings_OscSendPortAssignment_6(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFMFSettingsAccess().getOscSendPortAssignment_6();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FMFSettings_OscSendPortKeyword_5(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("oscSendPort",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("oscSendPort");
		if(valueSerializer.isValid(obj.getEObject(), grammarAccess.getFMFSettingsAccess().getOscSendPortINTTerminalRuleCall_6_0(), value, null)) {
			type = AssignmentType.TERMINAL_RULE_CALL;
			element = grammarAccess.getFMFSettingsAccess().getOscSendPortINTTerminalRuleCall_6_0();
			return obj;
		}
		return null;
	}

}

// "TuioPort:"
protected class FMFSettings_TuioPortKeyword_7 extends KeywordToken  {
	
	public FMFSettings_TuioPortKeyword_7(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFMFSettingsAccess().getTuioPortKeyword_7();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FMFSettings_OscSendPortAssignment_6(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// tuioPort=INT
protected class FMFSettings_TuioPortAssignment_8 extends AssignmentToken  {
	
	public FMFSettings_TuioPortAssignment_8(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFMFSettingsAccess().getTuioPortAssignment_8();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FMFSettings_TuioPortKeyword_7(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("tuioPort",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("tuioPort");
		if(valueSerializer.isValid(obj.getEObject(), grammarAccess.getFMFSettingsAccess().getTuioPortINTTerminalRuleCall_8_0(), value, null)) {
			type = AssignmentType.TERMINAL_RULE_CALL;
			element = grammarAccess.getFMFSettingsAccess().getTuioPortINTTerminalRuleCall_8_0();
			return obj;
		}
		return null;
	}

}

// "liveRate:"
protected class FMFSettings_LiveRateKeyword_9 extends KeywordToken  {
	
	public FMFSettings_LiveRateKeyword_9(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFMFSettingsAccess().getLiveRateKeyword_9();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FMFSettings_TuioPortAssignment_8(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// liveRate=INT
protected class FMFSettings_LiveRateAssignment_10 extends AssignmentToken  {
	
	public FMFSettings_LiveRateAssignment_10(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFMFSettingsAccess().getLiveRateAssignment_10();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FMFSettings_LiveRateKeyword_9(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("liveRate",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("liveRate");
		if(valueSerializer.isValid(obj.getEObject(), grammarAccess.getFMFSettingsAccess().getLiveRateINTTerminalRuleCall_10_0(), value, null)) {
			type = AssignmentType.TERMINAL_RULE_CALL;
			element = grammarAccess.getFMFSettingsAccess().getLiveRateINTTerminalRuleCall_10_0();
			return obj;
		}
		return null;
	}

}

// "processingRate:"
protected class FMFSettings_ProcessingRateKeyword_11 extends KeywordToken  {
	
	public FMFSettings_ProcessingRateKeyword_11(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFMFSettingsAccess().getProcessingRateKeyword_11();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FMFSettings_LiveRateAssignment_10(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// processingRate=INT
protected class FMFSettings_ProcessingRateAssignment_12 extends AssignmentToken  {
	
	public FMFSettings_ProcessingRateAssignment_12(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFMFSettingsAccess().getProcessingRateAssignment_12();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FMFSettings_ProcessingRateKeyword_11(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("processingRate",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("processingRate");
		if(valueSerializer.isValid(obj.getEObject(), grammarAccess.getFMFSettingsAccess().getProcessingRateINTTerminalRuleCall_12_0(), value, null)) {
			type = AssignmentType.TERMINAL_RULE_CALL;
			element = grammarAccess.getFMFSettingsAccess().getProcessingRateINTTerminalRuleCall_12_0();
			return obj;
		}
		return null;
	}

}

// "}"
protected class FMFSettings_RightCurlyBracketKeyword_13 extends KeywordToken  {
	
	public FMFSettings_RightCurlyBracketKeyword_13(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFMFSettingsAccess().getRightCurlyBracketKeyword_13();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FMFSettings_ProcessingRateAssignment_12(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}


/************ end Rule FMFSettings ****************/

}
