/*
 * generated by Xtext
 */
package net.sf.fmurf.ui.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FmurfUiDSLUiModule extends net.sf.fmurf.ui.ui.AbstractFmurfUiDSLUiModule {
	public FmurfUiDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
