
/*
 * generated by Xtext
 */
 
package net.sf.fmurf.ui.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class FmurfUiDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return net.sf.fmurf.ui.ui.internal.FmurfUiDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return net.sf.fmurf.ui.ui.internal.FmurfUiDSLActivator.getInstance().getInjector("net.sf.fmurf.ui.FmurfUiDSL");
	}
	
}
