/*
* generated by Xtext
*/
package net.sf.fmurf.ui.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class FmurfUiDSLTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
