/*
 * generated by Xtext
 */
package net.sf.fmurf.ui;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FmurfUiDSLRuntimeModule extends net.sf.fmurf.ui.AbstractFmurfUiDSLRuntimeModule {

}
