/*
* generated by Xtext
*/
package net.sf.fmurf.ui.parser.antlr;

import net.sf.fmurf.ui.services.FmurfUiDSLGrammarAccess;

import org.antlr.runtime.CharStream;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.IParseResult;
import org.eclipse.xtext.parser.ParseException;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;

public class FmurfUiDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FmurfUiDSLGrammarAccess grammarAccess;
	
	@Override
	protected IParseResult parse(String ruleName, CharStream in) {
		TokenSource tokenSource = createLexer(in);
		XtextTokenStream tokenStream = createTokenStream(tokenSource);
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
		net.sf.fmurf.ui.parser.antlr.internal.InternalFmurfUiDSLParser parser = createParser(tokenStream);
		parser.setTokenTypeMap(getTokenDefProvider().getTokenDefMap());
		parser.setSyntaxErrorProvider(getSyntaxErrorProvider());
		parser.setUnorderedGroupHelper(getUnorderedGroupHelper().get());
		try {
			if(ruleName != null)
				return parser.parse(ruleName);
			return parser.parse();
		} catch (Exception re) {
			throw new ParseException(re.getMessage(),re);
		}
	}
	
	protected net.sf.fmurf.ui.parser.antlr.internal.InternalFmurfUiDSLParser createParser(XtextTokenStream stream) {
		return new net.sf.fmurf.ui.parser.antlr.internal.InternalFmurfUiDSLParser(stream, getElementFactory(), getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "FMFUI";
	}
	
	public FmurfUiDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FmurfUiDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
