/*
* generated by Xtext
*/

package net.sf.fmurf.ui.services;

import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

import com.google.inject.Inject;
import com.google.inject.Singleton;

@Singleton
public class FmurfUiDSLGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class FMFUIElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FMFUI");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSettingsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cSettingsFMFSettingsParserRuleCall_0_0 = (RuleCall)cSettingsAssignment_0.eContents().get(0);
		private final Assignment cFiducialsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cFiducialsFiducialParserRuleCall_1_0 = (RuleCall)cFiducialsAssignment_1.eContents().get(0);
		
		//FMFUI:
		//	settings=FMFSettings fiducials+=Fiducial*;
		public ParserRule getRule() { return rule; }

		//settings=FMFSettings fiducials+=Fiducial*
		public Group getGroup() { return cGroup; }

		//settings=FMFSettings
		public Assignment getSettingsAssignment_0() { return cSettingsAssignment_0; }

		//FMFSettings
		public RuleCall getSettingsFMFSettingsParserRuleCall_0_0() { return cSettingsFMFSettingsParserRuleCall_0_0; }

		//fiducials+=Fiducial*
		public Assignment getFiducialsAssignment_1() { return cFiducialsAssignment_1; }

		//Fiducial
		public RuleCall getFiducialsFiducialParserRuleCall_1_0() { return cFiducialsFiducialParserRuleCall_1_0; }
	}

	public class FiducialElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Fiducial");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFiducialKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cUidAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cUidINTTerminalRuleCall_3_0 = (RuleCall)cUidAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cStyleKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStyleAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cStyleFMFFidStyleEnumEnumRuleCall_6_0 = (RuleCall)cStyleAssignment_6.eContents().get(0);
		private final Keyword cKindKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cKindAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cKindFMFKindEnumRuleCall_8_0 = (RuleCall)cKindAssignment_8.eContents().get(0);
		private final Keyword cForegroundKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cFgAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cFgFMFFidColorEnumEnumRuleCall_10_0 = (RuleCall)cFgAssignment_10.eContents().get(0);
		private final Keyword cBackgroundKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cBgAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cBgFMFFidColorEnumEnumRuleCall_12_0 = (RuleCall)cBgAssignment_12.eContents().get(0);
		private final Keyword cRadiusKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cRadiusAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cRadiusINTTerminalRuleCall_14_0 = (RuleCall)cRadiusAssignment_14.eContents().get(0);
		private final Keyword cProximaKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cProximaAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cProximaINTTerminalRuleCall_16_0 = (RuleCall)cProximaAssignment_16.eContents().get(0);
		private final Keyword cProximaVisibleKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Assignment cProximaVisibleAssignment_18 = (Assignment)cGroup.eContents().get(18);
		private final RuleCall cProximaVisibleFMFProximaVisibleEnumEnumRuleCall_18_0 = (RuleCall)cProximaVisibleAssignment_18.eContents().get(0);
		private final Keyword cFunctionKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Assignment cFunctionAssignment_20 = (Assignment)cGroup.eContents().get(20);
		private final RuleCall cFunctionFMFFidFunctionEnumEnumRuleCall_20_0 = (RuleCall)cFunctionAssignment_20.eContents().get(0);
		private final Keyword cRangeKeyword_21 = (Keyword)cGroup.eContents().get(21);
		private final Assignment cRangeAssignment_22 = (Assignment)cGroup.eContents().get(22);
		private final RuleCall cRangeINTTerminalRuleCall_22_0 = (RuleCall)cRangeAssignment_22.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_23 = (Keyword)cGroup.eContents().get(23);
		
		//Fiducial:
		//	"fiducial" name=ID ":" uid=INT "{" "style:" style=FMFFidStyleEnum "kind:" kind=FMFKind "foreground:"
		//	fg=FMFFidColorEnum "background:" bg=FMFFidColorEnum "radius:" radius=INT "proxima:" proxima=INT "proximaVisible:"
		//	proximaVisible=FMFProximaVisibleEnum "function:" function=FMFFidFunctionEnum "range:" range=INT "}";
		public ParserRule getRule() { return rule; }

		//"fiducial" name=ID ":" uid=INT "{" "style:" style=FMFFidStyleEnum "kind:" kind=FMFKind "foreground:" fg=FMFFidColorEnum
		//"background:" bg=FMFFidColorEnum "radius:" radius=INT "proxima:" proxima=INT "proximaVisible:"
		//proximaVisible=FMFProximaVisibleEnum "function:" function=FMFFidFunctionEnum "range:" range=INT "}"
		public Group getGroup() { return cGroup; }

		//"fiducial"
		public Keyword getFiducialKeyword_0() { return cFiducialKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }

		//uid=INT
		public Assignment getUidAssignment_3() { return cUidAssignment_3; }

		//INT
		public RuleCall getUidINTTerminalRuleCall_3_0() { return cUidINTTerminalRuleCall_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//"style:"
		public Keyword getStyleKeyword_5() { return cStyleKeyword_5; }

		//style=FMFFidStyleEnum
		public Assignment getStyleAssignment_6() { return cStyleAssignment_6; }

		//FMFFidStyleEnum
		public RuleCall getStyleFMFFidStyleEnumEnumRuleCall_6_0() { return cStyleFMFFidStyleEnumEnumRuleCall_6_0; }

		//"kind:"
		public Keyword getKindKeyword_7() { return cKindKeyword_7; }

		//kind=FMFKind
		public Assignment getKindAssignment_8() { return cKindAssignment_8; }

		//FMFKind
		public RuleCall getKindFMFKindEnumRuleCall_8_0() { return cKindFMFKindEnumRuleCall_8_0; }

		//"foreground:"
		public Keyword getForegroundKeyword_9() { return cForegroundKeyword_9; }

		//fg=FMFFidColorEnum
		public Assignment getFgAssignment_10() { return cFgAssignment_10; }

		//FMFFidColorEnum
		public RuleCall getFgFMFFidColorEnumEnumRuleCall_10_0() { return cFgFMFFidColorEnumEnumRuleCall_10_0; }

		//"background:"
		public Keyword getBackgroundKeyword_11() { return cBackgroundKeyword_11; }

		//bg=FMFFidColorEnum
		public Assignment getBgAssignment_12() { return cBgAssignment_12; }

		//FMFFidColorEnum
		public RuleCall getBgFMFFidColorEnumEnumRuleCall_12_0() { return cBgFMFFidColorEnumEnumRuleCall_12_0; }

		//"radius:"
		public Keyword getRadiusKeyword_13() { return cRadiusKeyword_13; }

		//radius=INT
		public Assignment getRadiusAssignment_14() { return cRadiusAssignment_14; }

		//INT
		public RuleCall getRadiusINTTerminalRuleCall_14_0() { return cRadiusINTTerminalRuleCall_14_0; }

		//"proxima:"
		public Keyword getProximaKeyword_15() { return cProximaKeyword_15; }

		//proxima=INT
		public Assignment getProximaAssignment_16() { return cProximaAssignment_16; }

		//INT
		public RuleCall getProximaINTTerminalRuleCall_16_0() { return cProximaINTTerminalRuleCall_16_0; }

		//"proximaVisible:"
		public Keyword getProximaVisibleKeyword_17() { return cProximaVisibleKeyword_17; }

		//proximaVisible=FMFProximaVisibleEnum
		public Assignment getProximaVisibleAssignment_18() { return cProximaVisibleAssignment_18; }

		//FMFProximaVisibleEnum
		public RuleCall getProximaVisibleFMFProximaVisibleEnumEnumRuleCall_18_0() { return cProximaVisibleFMFProximaVisibleEnumEnumRuleCall_18_0; }

		//"function:"
		public Keyword getFunctionKeyword_19() { return cFunctionKeyword_19; }

		//function=FMFFidFunctionEnum
		public Assignment getFunctionAssignment_20() { return cFunctionAssignment_20; }

		//FMFFidFunctionEnum
		public RuleCall getFunctionFMFFidFunctionEnumEnumRuleCall_20_0() { return cFunctionFMFFidFunctionEnumEnumRuleCall_20_0; }

		//"range:"
		public Keyword getRangeKeyword_21() { return cRangeKeyword_21; }

		//range=INT
		public Assignment getRangeAssignment_22() { return cRangeAssignment_22; }

		//INT
		public RuleCall getRangeINTTerminalRuleCall_22_0() { return cRangeINTTerminalRuleCall_22_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_23() { return cRightCurlyBracketKeyword_23; }
	}

	public class FMFSettingsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FMFSettings");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSettingsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cOscReceivePortKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cOscReceivePortAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cOscReceivePortINTTerminalRuleCall_2_0 = (RuleCall)cOscReceivePortAssignment_2.eContents().get(0);
		private final Keyword cOscSendAddressKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cOscSendAddressAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cOscSendAddressSTRINGTerminalRuleCall_4_0 = (RuleCall)cOscSendAddressAssignment_4.eContents().get(0);
		private final Keyword cOscSendPortKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cOscSendPortAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cOscSendPortINTTerminalRuleCall_6_0 = (RuleCall)cOscSendPortAssignment_6.eContents().get(0);
		private final Keyword cTuioPortKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cTuioPortAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cTuioPortINTTerminalRuleCall_8_0 = (RuleCall)cTuioPortAssignment_8.eContents().get(0);
		private final Keyword cLiveRateKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cLiveRateAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cLiveRateINTTerminalRuleCall_10_0 = (RuleCall)cLiveRateAssignment_10.eContents().get(0);
		private final Keyword cProcessingRateKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cProcessingRateAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cProcessingRateINTTerminalRuleCall_12_0 = (RuleCall)cProcessingRateAssignment_12.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//FMFSettings:
		//	"settings : {" "OscReceivePort:" oscReceivePort=INT "OscSendAddress:" oscSendAddress=STRING "OscSendPort:"
		//	oscSendPort=INT "TuioPort:" tuioPort=INT "liveRate:" liveRate=INT "processingRate:" processingRate=INT "}";
		public ParserRule getRule() { return rule; }

		//"settings : {" "OscReceivePort:" oscReceivePort=INT "OscSendAddress:" oscSendAddress=STRING "OscSendPort:"
		//oscSendPort=INT "TuioPort:" tuioPort=INT "liveRate:" liveRate=INT "processingRate:" processingRate=INT "}"
		public Group getGroup() { return cGroup; }

		//"settings : {"
		public Keyword getSettingsKeyword_0() { return cSettingsKeyword_0; }

		//"OscReceivePort:"
		public Keyword getOscReceivePortKeyword_1() { return cOscReceivePortKeyword_1; }

		//oscReceivePort=INT
		public Assignment getOscReceivePortAssignment_2() { return cOscReceivePortAssignment_2; }

		//INT
		public RuleCall getOscReceivePortINTTerminalRuleCall_2_0() { return cOscReceivePortINTTerminalRuleCall_2_0; }

		//"OscSendAddress:"
		public Keyword getOscSendAddressKeyword_3() { return cOscSendAddressKeyword_3; }

		//oscSendAddress=STRING
		public Assignment getOscSendAddressAssignment_4() { return cOscSendAddressAssignment_4; }

		//STRING
		public RuleCall getOscSendAddressSTRINGTerminalRuleCall_4_0() { return cOscSendAddressSTRINGTerminalRuleCall_4_0; }

		//"OscSendPort:"
		public Keyword getOscSendPortKeyword_5() { return cOscSendPortKeyword_5; }

		//oscSendPort=INT
		public Assignment getOscSendPortAssignment_6() { return cOscSendPortAssignment_6; }

		//INT
		public RuleCall getOscSendPortINTTerminalRuleCall_6_0() { return cOscSendPortINTTerminalRuleCall_6_0; }

		//"TuioPort:"
		public Keyword getTuioPortKeyword_7() { return cTuioPortKeyword_7; }

		//tuioPort=INT
		public Assignment getTuioPortAssignment_8() { return cTuioPortAssignment_8; }

		//INT
		public RuleCall getTuioPortINTTerminalRuleCall_8_0() { return cTuioPortINTTerminalRuleCall_8_0; }

		//"liveRate:"
		public Keyword getLiveRateKeyword_9() { return cLiveRateKeyword_9; }

		//liveRate=INT
		public Assignment getLiveRateAssignment_10() { return cLiveRateAssignment_10; }

		//INT
		public RuleCall getLiveRateINTTerminalRuleCall_10_0() { return cLiveRateINTTerminalRuleCall_10_0; }

		//"processingRate:"
		public Keyword getProcessingRateKeyword_11() { return cProcessingRateKeyword_11; }

		//processingRate=INT
		public Assignment getProcessingRateAssignment_12() { return cProcessingRateAssignment_12; }

		//INT
		public RuleCall getProcessingRateINTTerminalRuleCall_12_0() { return cProcessingRateINTTerminalRuleCall_12_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}
	
	
	public class FMFProximaVisibleEnumElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "FMFProximaVisibleEnum");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cVISIBLEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cVISIBLEVISIBLEKeyword_0_0 = (Keyword)cVISIBLEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cHIDDENEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cHIDDENHIDDENKeyword_1_0 = (Keyword)cHIDDENEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum FMFProximaVisibleEnum:
		//	VISIBLE | HIDDEN;
		public EnumRule getRule() { return rule; }

		//VISIBLE | HIDDEN
		public Alternatives getAlternatives() { return cAlternatives; }

		//VISIBLE
		public EnumLiteralDeclaration getVISIBLEEnumLiteralDeclaration_0() { return cVISIBLEEnumLiteralDeclaration_0; }

		//"VISIBLE"
		public Keyword getVISIBLEVISIBLEKeyword_0_0() { return cVISIBLEVISIBLEKeyword_0_0; }

		//HIDDEN
		public EnumLiteralDeclaration getHIDDENEnumLiteralDeclaration_1() { return cHIDDENEnumLiteralDeclaration_1; }

		//"HIDDEN"
		public Keyword getHIDDENHIDDENKeyword_1_0() { return cHIDDENHIDDENKeyword_1_0; }
	}

	public class FMFFidStyleEnumElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "FMFFidStyleEnum");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cDISCEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cDISCDISCKeyword_0_0 = (Keyword)cDISCEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSQUAREEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSQUARESQUAREKeyword_1_0 = (Keyword)cSQUAREEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cPENTAGONEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cPENTAGONPENTAGONKeyword_2_0 = (Keyword)cPENTAGONEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cHEXAGONEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cHEXAGONHEXAGONKeyword_3_0 = (Keyword)cHEXAGONEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cEIGHTSTAREnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cEIGHTSTAREIGHTSTARKeyword_4_0 = (Keyword)cEIGHTSTAREnumLiteralDeclaration_4.eContents().get(0);
		
		//enum FMFFidStyleEnum:
		//	DISC | SQUARE | PENTAGON | HEXAGON | EIGHTSTAR;
		public EnumRule getRule() { return rule; }

		//DISC | SQUARE | PENTAGON | HEXAGON | EIGHTSTAR
		public Alternatives getAlternatives() { return cAlternatives; }

		//DISC
		public EnumLiteralDeclaration getDISCEnumLiteralDeclaration_0() { return cDISCEnumLiteralDeclaration_0; }

		//"DISC"
		public Keyword getDISCDISCKeyword_0_0() { return cDISCDISCKeyword_0_0; }

		//SQUARE
		public EnumLiteralDeclaration getSQUAREEnumLiteralDeclaration_1() { return cSQUAREEnumLiteralDeclaration_1; }

		//"SQUARE"
		public Keyword getSQUARESQUAREKeyword_1_0() { return cSQUARESQUAREKeyword_1_0; }

		//PENTAGON
		public EnumLiteralDeclaration getPENTAGONEnumLiteralDeclaration_2() { return cPENTAGONEnumLiteralDeclaration_2; }

		//"PENTAGON"
		public Keyword getPENTAGONPENTAGONKeyword_2_0() { return cPENTAGONPENTAGONKeyword_2_0; }

		//HEXAGON
		public EnumLiteralDeclaration getHEXAGONEnumLiteralDeclaration_3() { return cHEXAGONEnumLiteralDeclaration_3; }

		//"HEXAGON"
		public Keyword getHEXAGONHEXAGONKeyword_3_0() { return cHEXAGONHEXAGONKeyword_3_0; }

		//EIGHTSTAR
		public EnumLiteralDeclaration getEIGHTSTAREnumLiteralDeclaration_4() { return cEIGHTSTAREnumLiteralDeclaration_4; }

		//"EIGHTSTAR"
		public Keyword getEIGHTSTAREIGHTSTARKeyword_4_0() { return cEIGHTSTAREIGHTSTARKeyword_4_0; }
	}

	public class FMFKindElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "FMFKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSIN_OSCEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSIN_OSCSIN_OSCKeyword_0_0 = (Keyword)cSIN_OSCEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSQR_OSCEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSQR_OSCSQR_OSCKeyword_1_0 = (Keyword)cSQR_OSCEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cPULSE_OSCEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cPULSE_OSCPULSE_OSCKeyword_2_0 = (Keyword)cPULSE_OSCEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cTRI_OSCEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cTRI_OSCTRI_OSCKeyword_3_0 = (Keyword)cTRI_OSCEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cSAW_OSCEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cSAW_OSCSAW_OSCKeyword_4_0 = (Keyword)cSAW_OSCEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cSEQUENCEREnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cSEQUENCERSEQUENCERKeyword_5_0 = (Keyword)cSEQUENCEREnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cSAMPLEREnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cSAMPLERSAMPLERKeyword_6_0 = (Keyword)cSAMPLEREnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cECHOEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cECHOECHOKeyword_7_0 = (Keyword)cECHOEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cREVERBEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cREVERBREVERBKeyword_8_0 = (Keyword)cREVERBEnumLiteralDeclaration_8.eContents().get(0);
		
		//enum FMFKind:
		//	SIN_OSC | SQR_OSC | PULSE_OSC | TRI_OSC | SAW_OSC | SEQUENCER | SAMPLER | ECHO | REVERB;
		public EnumRule getRule() { return rule; }

		//SIN_OSC | SQR_OSC | PULSE_OSC | TRI_OSC | SAW_OSC | SEQUENCER | SAMPLER | ECHO | REVERB
		public Alternatives getAlternatives() { return cAlternatives; }

		//SIN_OSC
		public EnumLiteralDeclaration getSIN_OSCEnumLiteralDeclaration_0() { return cSIN_OSCEnumLiteralDeclaration_0; }

		//"SIN_OSC"
		public Keyword getSIN_OSCSIN_OSCKeyword_0_0() { return cSIN_OSCSIN_OSCKeyword_0_0; }

		//SQR_OSC
		public EnumLiteralDeclaration getSQR_OSCEnumLiteralDeclaration_1() { return cSQR_OSCEnumLiteralDeclaration_1; }

		//"SQR_OSC"
		public Keyword getSQR_OSCSQR_OSCKeyword_1_0() { return cSQR_OSCSQR_OSCKeyword_1_0; }

		//PULSE_OSC
		public EnumLiteralDeclaration getPULSE_OSCEnumLiteralDeclaration_2() { return cPULSE_OSCEnumLiteralDeclaration_2; }

		//"PULSE_OSC"
		public Keyword getPULSE_OSCPULSE_OSCKeyword_2_0() { return cPULSE_OSCPULSE_OSCKeyword_2_0; }

		//TRI_OSC
		public EnumLiteralDeclaration getTRI_OSCEnumLiteralDeclaration_3() { return cTRI_OSCEnumLiteralDeclaration_3; }

		//"TRI_OSC"
		public Keyword getTRI_OSCTRI_OSCKeyword_3_0() { return cTRI_OSCTRI_OSCKeyword_3_0; }

		//SAW_OSC
		public EnumLiteralDeclaration getSAW_OSCEnumLiteralDeclaration_4() { return cSAW_OSCEnumLiteralDeclaration_4; }

		//"SAW_OSC"
		public Keyword getSAW_OSCSAW_OSCKeyword_4_0() { return cSAW_OSCSAW_OSCKeyword_4_0; }

		//SEQUENCER
		public EnumLiteralDeclaration getSEQUENCEREnumLiteralDeclaration_5() { return cSEQUENCEREnumLiteralDeclaration_5; }

		//"SEQUENCER"
		public Keyword getSEQUENCERSEQUENCERKeyword_5_0() { return cSEQUENCERSEQUENCERKeyword_5_0; }

		//SAMPLER
		public EnumLiteralDeclaration getSAMPLEREnumLiteralDeclaration_6() { return cSAMPLEREnumLiteralDeclaration_6; }

		//"SAMPLER"
		public Keyword getSAMPLERSAMPLERKeyword_6_0() { return cSAMPLERSAMPLERKeyword_6_0; }

		//ECHO
		public EnumLiteralDeclaration getECHOEnumLiteralDeclaration_7() { return cECHOEnumLiteralDeclaration_7; }

		//"ECHO"
		public Keyword getECHOECHOKeyword_7_0() { return cECHOECHOKeyword_7_0; }

		//REVERB
		public EnumLiteralDeclaration getREVERBEnumLiteralDeclaration_8() { return cREVERBEnumLiteralDeclaration_8; }

		//"REVERB"
		public Keyword getREVERBREVERBKeyword_8_0() { return cREVERBREVERBKeyword_8_0; }
	}

	public class FMFFidFunctionEnumElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "FMFFidFunctionEnum");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cKNOBEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cKNOBKNOBKeyword_0_0 = (Keyword)cKNOBEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cNONEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cNONENONEKeyword_1_0 = (Keyword)cNONEEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum FMFFidFunctionEnum:
		//	KNOB | NONE;
		public EnumRule getRule() { return rule; }

		//KNOB | NONE
		public Alternatives getAlternatives() { return cAlternatives; }

		//KNOB
		public EnumLiteralDeclaration getKNOBEnumLiteralDeclaration_0() { return cKNOBEnumLiteralDeclaration_0; }

		//"KNOB"
		public Keyword getKNOBKNOBKeyword_0_0() { return cKNOBKNOBKeyword_0_0; }

		//NONE
		public EnumLiteralDeclaration getNONEEnumLiteralDeclaration_1() { return cNONEEnumLiteralDeclaration_1; }

		//"NONE"
		public Keyword getNONENONEKeyword_1_0() { return cNONENONEKeyword_1_0; }
	}

	public class FMFFidKindElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "FMFFidKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSinOscEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSinOscSinOscKeyword_0_0 = (Keyword)cSinOscEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSqrOscEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSqrOscSqrOscKeyword_1_0 = (Keyword)cSqrOscEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cTriOscEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cTriOscTriOscKeyword_2_0 = (Keyword)cTriOscEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cSawOscEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cSawOscSawOscKeyword_3_0 = (Keyword)cSawOscEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cPulseOscEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cPulseOscPulseOscKeyword_4_0 = (Keyword)cPulseOscEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cPhasorEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cPhasorPhasorKeyword_5_0 = (Keyword)cPhasorEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cSequencerEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cSequencerSequencerKeyword_6_0 = (Keyword)cSequencerEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cSamplerEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cSamplerSamplerKeyword_7_0 = (Keyword)cSamplerEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cReverbEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cReverbReverbKeyword_8_0 = (Keyword)cReverbEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cEchoEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cEchoEchoKeyword_9_0 = (Keyword)cEchoEnumLiteralDeclaration_9.eContents().get(0);
		
		//enum FMFFidKind:
		//	SinOsc | SqrOsc | TriOsc | SawOsc | PulseOsc | Phasor | Sequencer | Sampler | Reverb | Echo;
		public EnumRule getRule() { return rule; }

		//SinOsc | SqrOsc | TriOsc | SawOsc | PulseOsc | Phasor | Sequencer | Sampler | Reverb | Echo
		public Alternatives getAlternatives() { return cAlternatives; }

		//SinOsc
		public EnumLiteralDeclaration getSinOscEnumLiteralDeclaration_0() { return cSinOscEnumLiteralDeclaration_0; }

		//"SinOsc"
		public Keyword getSinOscSinOscKeyword_0_0() { return cSinOscSinOscKeyword_0_0; }

		//SqrOsc
		public EnumLiteralDeclaration getSqrOscEnumLiteralDeclaration_1() { return cSqrOscEnumLiteralDeclaration_1; }

		//"SqrOsc"
		public Keyword getSqrOscSqrOscKeyword_1_0() { return cSqrOscSqrOscKeyword_1_0; }

		//TriOsc
		public EnumLiteralDeclaration getTriOscEnumLiteralDeclaration_2() { return cTriOscEnumLiteralDeclaration_2; }

		//"TriOsc"
		public Keyword getTriOscTriOscKeyword_2_0() { return cTriOscTriOscKeyword_2_0; }

		//SawOsc
		public EnumLiteralDeclaration getSawOscEnumLiteralDeclaration_3() { return cSawOscEnumLiteralDeclaration_3; }

		//"SawOsc"
		public Keyword getSawOscSawOscKeyword_3_0() { return cSawOscSawOscKeyword_3_0; }

		//PulseOsc
		public EnumLiteralDeclaration getPulseOscEnumLiteralDeclaration_4() { return cPulseOscEnumLiteralDeclaration_4; }

		//"PulseOsc"
		public Keyword getPulseOscPulseOscKeyword_4_0() { return cPulseOscPulseOscKeyword_4_0; }

		//Phasor
		public EnumLiteralDeclaration getPhasorEnumLiteralDeclaration_5() { return cPhasorEnumLiteralDeclaration_5; }

		//"Phasor"
		public Keyword getPhasorPhasorKeyword_5_0() { return cPhasorPhasorKeyword_5_0; }

		//Sequencer
		public EnumLiteralDeclaration getSequencerEnumLiteralDeclaration_6() { return cSequencerEnumLiteralDeclaration_6; }

		//"Sequencer"
		public Keyword getSequencerSequencerKeyword_6_0() { return cSequencerSequencerKeyword_6_0; }

		//Sampler
		public EnumLiteralDeclaration getSamplerEnumLiteralDeclaration_7() { return cSamplerEnumLiteralDeclaration_7; }

		//"Sampler"
		public Keyword getSamplerSamplerKeyword_7_0() { return cSamplerSamplerKeyword_7_0; }

		//Reverb
		public EnumLiteralDeclaration getReverbEnumLiteralDeclaration_8() { return cReverbEnumLiteralDeclaration_8; }

		//"Reverb"
		public Keyword getReverbReverbKeyword_8_0() { return cReverbReverbKeyword_8_0; }

		//Echo
		public EnumLiteralDeclaration getEchoEnumLiteralDeclaration_9() { return cEchoEnumLiteralDeclaration_9; }

		//"Echo"
		public Keyword getEchoEchoKeyword_9_0() { return cEchoEchoKeyword_9_0; }
	}

	public class FMFFidColorEnumElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "FMFFidColorEnum");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cAquamarineEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cAquamarineAquamarineKeyword_0_0 = (Keyword)cAquamarineEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBakers_ChocolateEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBakers_ChocolateBakers_ChocolateKeyword_1_0 = (Keyword)cBakers_ChocolateEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBlackEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBlackBlackKeyword_2_0 = (Keyword)cBlackEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cBlueEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cBlueBlueKeyword_3_0 = (Keyword)cBlueEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cBrassEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cBrassBrassKeyword_4_0 = (Keyword)cBrassEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cBright_GoldEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cBright_GoldBright_GoldKeyword_5_0 = (Keyword)cBright_GoldEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cBrownEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cBrownBrownKeyword_6_0 = (Keyword)cBrownEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cBronzeEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cBronzeBronzeKeyword_7_0 = (Keyword)cBronzeEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cGoldEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cGoldGoldKeyword_8_0 = (Keyword)cGoldEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cGreyEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cGreyGreyKeyword_9_0 = (Keyword)cGreyEnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cGreenEnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cGreenGreenKeyword_10_0 = (Keyword)cGreenEnumLiteralDeclaration_10.eContents().get(0);
		private final EnumLiteralDeclaration cCopperEnumLiteralDeclaration_11 = (EnumLiteralDeclaration)cAlternatives.eContents().get(11);
		private final Keyword cCopperCopperKeyword_11_0 = (Keyword)cCopperEnumLiteralDeclaration_11.eContents().get(0);
		private final EnumLiteralDeclaration cCoralEnumLiteralDeclaration_12 = (EnumLiteralDeclaration)cAlternatives.eContents().get(12);
		private final Keyword cCoralCoralKeyword_12_0 = (Keyword)cCoralEnumLiteralDeclaration_12.eContents().get(0);
		private final EnumLiteralDeclaration cCyanEnumLiteralDeclaration_13 = (EnumLiteralDeclaration)cAlternatives.eContents().get(13);
		private final Keyword cCyanCyanKeyword_13_0 = (Keyword)cCyanEnumLiteralDeclaration_13.eContents().get(0);
		private final EnumLiteralDeclaration cDark_GreenEnumLiteralDeclaration_14 = (EnumLiteralDeclaration)cAlternatives.eContents().get(14);
		private final Keyword cDark_GreenDark_GreenKeyword_14_0 = (Keyword)cDark_GreenEnumLiteralDeclaration_14.eContents().get(0);
		private final EnumLiteralDeclaration cGreen_YellowEnumLiteralDeclaration_15 = (EnumLiteralDeclaration)cAlternatives.eContents().get(15);
		private final Keyword cGreen_YellowGreen_YellowKeyword_15_0 = (Keyword)cGreen_YellowEnumLiteralDeclaration_15.eContents().get(0);
		private final EnumLiteralDeclaration cMagentaEnumLiteralDeclaration_16 = (EnumLiteralDeclaration)cAlternatives.eContents().get(16);
		private final Keyword cMagentaMagentaKeyword_16_0 = (Keyword)cMagentaEnumLiteralDeclaration_16.eContents().get(0);
		private final EnumLiteralDeclaration cMaroonEnumLiteralDeclaration_17 = (EnumLiteralDeclaration)cAlternatives.eContents().get(17);
		private final Keyword cMaroonMaroonKeyword_17_0 = (Keyword)cMaroonEnumLiteralDeclaration_17.eContents().get(0);
		private final EnumLiteralDeclaration cMedium_BlueEnumLiteralDeclaration_18 = (EnumLiteralDeclaration)cAlternatives.eContents().get(18);
		private final Keyword cMedium_BlueMedium_BlueKeyword_18_0 = (Keyword)cMedium_BlueEnumLiteralDeclaration_18.eContents().get(0);
		private final EnumLiteralDeclaration cSiennaEnumLiteralDeclaration_19 = (EnumLiteralDeclaration)cAlternatives.eContents().get(19);
		private final Keyword cSiennaSiennaKeyword_19_0 = (Keyword)cSiennaEnumLiteralDeclaration_19.eContents().get(0);
		private final EnumLiteralDeclaration cSilverEnumLiteralDeclaration_20 = (EnumLiteralDeclaration)cAlternatives.eContents().get(20);
		private final Keyword cSilverSilverKeyword_20_0 = (Keyword)cSilverEnumLiteralDeclaration_20.eContents().get(0);
		private final EnumLiteralDeclaration cSalmonEnumLiteralDeclaration_21 = (EnumLiteralDeclaration)cAlternatives.eContents().get(21);
		private final Keyword cSalmonSalmonKeyword_21_0 = (Keyword)cSalmonEnumLiteralDeclaration_21.eContents().get(0);
		private final EnumLiteralDeclaration cOrangeEnumLiteralDeclaration_22 = (EnumLiteralDeclaration)cAlternatives.eContents().get(22);
		private final Keyword cOrangeOrangeKeyword_22_0 = (Keyword)cOrangeEnumLiteralDeclaration_22.eContents().get(0);
		private final EnumLiteralDeclaration cPinkEnumLiteralDeclaration_23 = (EnumLiteralDeclaration)cAlternatives.eContents().get(23);
		private final Keyword cPinkPinkKeyword_23_0 = (Keyword)cPinkEnumLiteralDeclaration_23.eContents().get(0);
		private final EnumLiteralDeclaration cRedEnumLiteralDeclaration_24 = (EnumLiteralDeclaration)cAlternatives.eContents().get(24);
		private final Keyword cRedRedKeyword_24_0 = (Keyword)cRedEnumLiteralDeclaration_24.eContents().get(0);
		private final EnumLiteralDeclaration cSummer_SkyEnumLiteralDeclaration_25 = (EnumLiteralDeclaration)cAlternatives.eContents().get(25);
		private final Keyword cSummer_SkySummer_SkyKeyword_25_0 = (Keyword)cSummer_SkyEnumLiteralDeclaration_25.eContents().get(0);
		private final EnumLiteralDeclaration cTanEnumLiteralDeclaration_26 = (EnumLiteralDeclaration)cAlternatives.eContents().get(26);
		private final Keyword cTanTanKeyword_26_0 = (Keyword)cTanEnumLiteralDeclaration_26.eContents().get(0);
		private final EnumLiteralDeclaration cThistleEnumLiteralDeclaration_27 = (EnumLiteralDeclaration)cAlternatives.eContents().get(27);
		private final Keyword cThistleThistleKeyword_27_0 = (Keyword)cThistleEnumLiteralDeclaration_27.eContents().get(0);
		private final EnumLiteralDeclaration cTurquoiseEnumLiteralDeclaration_28 = (EnumLiteralDeclaration)cAlternatives.eContents().get(28);
		private final Keyword cTurquoiseTurquoiseKeyword_28_0 = (Keyword)cTurquoiseEnumLiteralDeclaration_28.eContents().get(0);
		private final EnumLiteralDeclaration cVery_Dark_BrownEnumLiteralDeclaration_29 = (EnumLiteralDeclaration)cAlternatives.eContents().get(29);
		private final Keyword cVery_Dark_BrownVery_Dark_BrownKeyword_29_0 = (Keyword)cVery_Dark_BrownEnumLiteralDeclaration_29.eContents().get(0);
		private final EnumLiteralDeclaration cVery_Light_GreyEnumLiteralDeclaration_30 = (EnumLiteralDeclaration)cAlternatives.eContents().get(30);
		private final Keyword cVery_Light_GreyVery_Light_GreyKeyword_30_0 = (Keyword)cVery_Light_GreyEnumLiteralDeclaration_30.eContents().get(0);
		private final EnumLiteralDeclaration cVioletEnumLiteralDeclaration_31 = (EnumLiteralDeclaration)cAlternatives.eContents().get(31);
		private final Keyword cVioletVioletKeyword_31_0 = (Keyword)cVioletEnumLiteralDeclaration_31.eContents().get(0);
		private final EnumLiteralDeclaration cViolet_RedEnumLiteralDeclaration_32 = (EnumLiteralDeclaration)cAlternatives.eContents().get(32);
		private final Keyword cViolet_RedViolet_RedKeyword_32_0 = (Keyword)cViolet_RedEnumLiteralDeclaration_32.eContents().get(0);
		private final EnumLiteralDeclaration cWheatEnumLiteralDeclaration_33 = (EnumLiteralDeclaration)cAlternatives.eContents().get(33);
		private final Keyword cWheatWheatKeyword_33_0 = (Keyword)cWheatEnumLiteralDeclaration_33.eContents().get(0);
		private final EnumLiteralDeclaration cWhiteEnumLiteralDeclaration_34 = (EnumLiteralDeclaration)cAlternatives.eContents().get(34);
		private final Keyword cWhiteWhiteKeyword_34_0 = (Keyword)cWhiteEnumLiteralDeclaration_34.eContents().get(0);
		private final EnumLiteralDeclaration cYellowEnumLiteralDeclaration_35 = (EnumLiteralDeclaration)cAlternatives.eContents().get(35);
		private final Keyword cYellowYellowKeyword_35_0 = (Keyword)cYellowEnumLiteralDeclaration_35.eContents().get(0);
		private final EnumLiteralDeclaration cYellow_GreenEnumLiteralDeclaration_36 = (EnumLiteralDeclaration)cAlternatives.eContents().get(36);
		private final Keyword cYellow_GreenYellow_GreenKeyword_36_0 = (Keyword)cYellow_GreenEnumLiteralDeclaration_36.eContents().get(0);
		private final EnumLiteralDeclaration cDark_YellowEnumLiteralDeclaration_37 = (EnumLiteralDeclaration)cAlternatives.eContents().get(37);
		private final Keyword cDark_YellowDark_YellowKeyword_37_0 = (Keyword)cDark_YellowEnumLiteralDeclaration_37.eContents().get(0);
		private final EnumLiteralDeclaration cBronze_IIEnumLiteralDeclaration_38 = (EnumLiteralDeclaration)cAlternatives.eContents().get(38);
		private final Keyword cBronze_IIBronze_IIKeyword_38_0 = (Keyword)cBronze_IIEnumLiteralDeclaration_38.eContents().get(0);
		private final EnumLiteralDeclaration cCadet_BlueEnumLiteralDeclaration_39 = (EnumLiteralDeclaration)cAlternatives.eContents().get(39);
		private final Keyword cCadet_BlueCadet_BlueKeyword_39_0 = (Keyword)cCadet_BlueEnumLiteralDeclaration_39.eContents().get(0);
		private final EnumLiteralDeclaration cCool_CopperEnumLiteralDeclaration_40 = (EnumLiteralDeclaration)cAlternatives.eContents().get(40);
		private final Keyword cCool_CopperCool_CopperKeyword_40_0 = (Keyword)cCool_CopperEnumLiteralDeclaration_40.eContents().get(0);
		private final EnumLiteralDeclaration cCorn_Flower_BlueEnumLiteralDeclaration_41 = (EnumLiteralDeclaration)cAlternatives.eContents().get(41);
		private final Keyword cCorn_Flower_BlueCorn_Flower_BlueKeyword_41_0 = (Keyword)cCorn_Flower_BlueEnumLiteralDeclaration_41.eContents().get(0);
		private final EnumLiteralDeclaration cDark_BrownEnumLiteralDeclaration_42 = (EnumLiteralDeclaration)cAlternatives.eContents().get(42);
		private final Keyword cDark_BrownDark_BrownKeyword_42_0 = (Keyword)cDark_BrownEnumLiteralDeclaration_42.eContents().get(0);
		private final EnumLiteralDeclaration cDark_Green_CopperEnumLiteralDeclaration_43 = (EnumLiteralDeclaration)cAlternatives.eContents().get(43);
		private final Keyword cDark_Green_CopperDark_Green_CopperKeyword_43_0 = (Keyword)cDark_Green_CopperEnumLiteralDeclaration_43.eContents().get(0);
		private final EnumLiteralDeclaration cDark_Olive_GreenEnumLiteralDeclaration_44 = (EnumLiteralDeclaration)cAlternatives.eContents().get(44);
		private final Keyword cDark_Olive_GreenDark_Olive_GreenKeyword_44_0 = (Keyword)cDark_Olive_GreenEnumLiteralDeclaration_44.eContents().get(0);
		private final EnumLiteralDeclaration cDark_OrchidEnumLiteralDeclaration_45 = (EnumLiteralDeclaration)cAlternatives.eContents().get(45);
		private final Keyword cDark_OrchidDark_OrchidKeyword_45_0 = (Keyword)cDark_OrchidEnumLiteralDeclaration_45.eContents().get(0);
		private final EnumLiteralDeclaration cDark_PurpleEnumLiteralDeclaration_46 = (EnumLiteralDeclaration)cAlternatives.eContents().get(46);
		private final Keyword cDark_PurpleDark_PurpleKeyword_46_0 = (Keyword)cDark_PurpleEnumLiteralDeclaration_46.eContents().get(0);
		private final EnumLiteralDeclaration cDark_Slate_BlueEnumLiteralDeclaration_47 = (EnumLiteralDeclaration)cAlternatives.eContents().get(47);
		private final Keyword cDark_Slate_BlueDark_Slate_BlueKeyword_47_0 = (Keyword)cDark_Slate_BlueEnumLiteralDeclaration_47.eContents().get(0);
		private final EnumLiteralDeclaration cDark_TurquoiseEnumLiteralDeclaration_48 = (EnumLiteralDeclaration)cAlternatives.eContents().get(48);
		private final Keyword cDark_TurquoiseDark_TurquoiseKeyword_48_0 = (Keyword)cDark_TurquoiseEnumLiteralDeclaration_48.eContents().get(0);
		private final EnumLiteralDeclaration cDark_TanEnumLiteralDeclaration_49 = (EnumLiteralDeclaration)cAlternatives.eContents().get(49);
		private final Keyword cDark_TanDark_TanKeyword_49_0 = (Keyword)cDark_TanEnumLiteralDeclaration_49.eContents().get(0);
		private final EnumLiteralDeclaration cDark_WoodEnumLiteralDeclaration_50 = (EnumLiteralDeclaration)cAlternatives.eContents().get(50);
		private final Keyword cDark_WoodDark_WoodKeyword_50_0 = (Keyword)cDark_WoodEnumLiteralDeclaration_50.eContents().get(0);
		private final EnumLiteralDeclaration cDim_GreyEnumLiteralDeclaration_51 = (EnumLiteralDeclaration)cAlternatives.eContents().get(51);
		private final Keyword cDim_GreyDim_GreyKeyword_51_0 = (Keyword)cDim_GreyEnumLiteralDeclaration_51.eContents().get(0);
		private final EnumLiteralDeclaration cDusty_RoseEnumLiteralDeclaration_52 = (EnumLiteralDeclaration)cAlternatives.eContents().get(52);
		private final Keyword cDusty_RoseDusty_RoseKeyword_52_0 = (Keyword)cDusty_RoseEnumLiteralDeclaration_52.eContents().get(0);
		private final EnumLiteralDeclaration cFeldsparEnumLiteralDeclaration_53 = (EnumLiteralDeclaration)cAlternatives.eContents().get(53);
		private final Keyword cFeldsparFeldsparKeyword_53_0 = (Keyword)cFeldsparEnumLiteralDeclaration_53.eContents().get(0);
		private final EnumLiteralDeclaration cFirebrickEnumLiteralDeclaration_54 = (EnumLiteralDeclaration)cAlternatives.eContents().get(54);
		private final Keyword cFirebrickFirebrickKeyword_54_0 = (Keyword)cFirebrickEnumLiteralDeclaration_54.eContents().get(0);
		private final EnumLiteralDeclaration cForest_GreenEnumLiteralDeclaration_55 = (EnumLiteralDeclaration)cAlternatives.eContents().get(55);
		private final Keyword cForest_GreenForest_GreenKeyword_55_0 = (Keyword)cForest_GreenEnumLiteralDeclaration_55.eContents().get(0);
		private final EnumLiteralDeclaration cGoldenrodEnumLiteralDeclaration_56 = (EnumLiteralDeclaration)cAlternatives.eContents().get(56);
		private final Keyword cGoldenrodGoldenrodKeyword_56_0 = (Keyword)cGoldenrodEnumLiteralDeclaration_56.eContents().get(0);
		private final EnumLiteralDeclaration cGreen_CopperEnumLiteralDeclaration_57 = (EnumLiteralDeclaration)cAlternatives.eContents().get(57);
		private final Keyword cGreen_CopperGreen_CopperKeyword_57_0 = (Keyword)cGreen_CopperEnumLiteralDeclaration_57.eContents().get(0);
		private final EnumLiteralDeclaration cHunter_GreenEnumLiteralDeclaration_58 = (EnumLiteralDeclaration)cAlternatives.eContents().get(58);
		private final Keyword cHunter_GreenHunter_GreenKeyword_58_0 = (Keyword)cHunter_GreenEnumLiteralDeclaration_58.eContents().get(0);
		private final EnumLiteralDeclaration cIndian_RedEnumLiteralDeclaration_59 = (EnumLiteralDeclaration)cAlternatives.eContents().get(59);
		private final Keyword cIndian_RedIndian_RedKeyword_59_0 = (Keyword)cIndian_RedEnumLiteralDeclaration_59.eContents().get(0);
		private final EnumLiteralDeclaration cKhakiEnumLiteralDeclaration_60 = (EnumLiteralDeclaration)cAlternatives.eContents().get(60);
		private final Keyword cKhakiKhakiKeyword_60_0 = (Keyword)cKhakiEnumLiteralDeclaration_60.eContents().get(0);
		private final EnumLiteralDeclaration cLight_BlueEnumLiteralDeclaration_61 = (EnumLiteralDeclaration)cAlternatives.eContents().get(61);
		private final Keyword cLight_BlueLight_BlueKeyword_61_0 = (Keyword)cLight_BlueEnumLiteralDeclaration_61.eContents().get(0);
		private final EnumLiteralDeclaration cLight_GreyEnumLiteralDeclaration_62 = (EnumLiteralDeclaration)cAlternatives.eContents().get(62);
		private final Keyword cLight_GreyLight_GreyKeyword_62_0 = (Keyword)cLight_GreyEnumLiteralDeclaration_62.eContents().get(0);
		private final EnumLiteralDeclaration cLight_Steel_BlueEnumLiteralDeclaration_63 = (EnumLiteralDeclaration)cAlternatives.eContents().get(63);
		private final Keyword cLight_Steel_BlueLight_Steel_BlueKeyword_63_0 = (Keyword)cLight_Steel_BlueEnumLiteralDeclaration_63.eContents().get(0);
		private final EnumLiteralDeclaration cLight_WoodEnumLiteralDeclaration_64 = (EnumLiteralDeclaration)cAlternatives.eContents().get(64);
		private final Keyword cLight_WoodLight_WoodKeyword_64_0 = (Keyword)cLight_WoodEnumLiteralDeclaration_64.eContents().get(0);
		private final EnumLiteralDeclaration cLime_GreenEnumLiteralDeclaration_65 = (EnumLiteralDeclaration)cAlternatives.eContents().get(65);
		private final Keyword cLime_GreenLime_GreenKeyword_65_0 = (Keyword)cLime_GreenEnumLiteralDeclaration_65.eContents().get(0);
		private final EnumLiteralDeclaration cMandarian_OrangeEnumLiteralDeclaration_66 = (EnumLiteralDeclaration)cAlternatives.eContents().get(66);
		private final Keyword cMandarian_OrangeMandarian_OrangeKeyword_66_0 = (Keyword)cMandarian_OrangeEnumLiteralDeclaration_66.eContents().get(0);
		private final EnumLiteralDeclaration cMedium_AquamarineEnumLiteralDeclaration_67 = (EnumLiteralDeclaration)cAlternatives.eContents().get(67);
		private final Keyword cMedium_AquamarineMedium_AquamarineKeyword_67_0 = (Keyword)cMedium_AquamarineEnumLiteralDeclaration_67.eContents().get(0);
		private final EnumLiteralDeclaration cMedium_Forest_GreenEnumLiteralDeclaration_68 = (EnumLiteralDeclaration)cAlternatives.eContents().get(68);
		private final Keyword cMedium_Forest_GreenMedium_Forest_GreenKeyword_68_0 = (Keyword)cMedium_Forest_GreenEnumLiteralDeclaration_68.eContents().get(0);
		private final EnumLiteralDeclaration cMedium_GoldenrodEnumLiteralDeclaration_69 = (EnumLiteralDeclaration)cAlternatives.eContents().get(69);
		private final Keyword cMedium_GoldenrodMedium_GoldenrodKeyword_69_0 = (Keyword)cMedium_GoldenrodEnumLiteralDeclaration_69.eContents().get(0);
		private final EnumLiteralDeclaration cMedium_OrchidEnumLiteralDeclaration_70 = (EnumLiteralDeclaration)cAlternatives.eContents().get(70);
		private final Keyword cMedium_OrchidMedium_OrchidKeyword_70_0 = (Keyword)cMedium_OrchidEnumLiteralDeclaration_70.eContents().get(0);
		private final EnumLiteralDeclaration cMedium_Sea_GreenEnumLiteralDeclaration_71 = (EnumLiteralDeclaration)cAlternatives.eContents().get(71);
		private final Keyword cMedium_Sea_GreenMedium_Sea_GreenKeyword_71_0 = (Keyword)cMedium_Sea_GreenEnumLiteralDeclaration_71.eContents().get(0);
		private final EnumLiteralDeclaration cMedium_Slate_BlueEnumLiteralDeclaration_72 = (EnumLiteralDeclaration)cAlternatives.eContents().get(72);
		private final Keyword cMedium_Slate_BlueMedium_Slate_BlueKeyword_72_0 = (Keyword)cMedium_Slate_BlueEnumLiteralDeclaration_72.eContents().get(0);
		private final EnumLiteralDeclaration cMedium_Spring_GreenEnumLiteralDeclaration_73 = (EnumLiteralDeclaration)cAlternatives.eContents().get(73);
		private final Keyword cMedium_Spring_GreenMedium_Spring_GreenKeyword_73_0 = (Keyword)cMedium_Spring_GreenEnumLiteralDeclaration_73.eContents().get(0);
		private final EnumLiteralDeclaration cMedium_TurquoiseEnumLiteralDeclaration_74 = (EnumLiteralDeclaration)cAlternatives.eContents().get(74);
		private final Keyword cMedium_TurquoiseMedium_TurquoiseKeyword_74_0 = (Keyword)cMedium_TurquoiseEnumLiteralDeclaration_74.eContents().get(0);
		private final EnumLiteralDeclaration cMedium_Violet_RedEnumLiteralDeclaration_75 = (EnumLiteralDeclaration)cAlternatives.eContents().get(75);
		private final Keyword cMedium_Violet_RedMedium_Violet_RedKeyword_75_0 = (Keyword)cMedium_Violet_RedEnumLiteralDeclaration_75.eContents().get(0);
		private final EnumLiteralDeclaration cMedium_WoodEnumLiteralDeclaration_76 = (EnumLiteralDeclaration)cAlternatives.eContents().get(76);
		private final Keyword cMedium_WoodMedium_WoodKeyword_76_0 = (Keyword)cMedium_WoodEnumLiteralDeclaration_76.eContents().get(0);
		private final EnumLiteralDeclaration cMidnight_BlueEnumLiteralDeclaration_77 = (EnumLiteralDeclaration)cAlternatives.eContents().get(77);
		private final Keyword cMidnight_BlueMidnight_BlueKeyword_77_0 = (Keyword)cMidnight_BlueEnumLiteralDeclaration_77.eContents().get(0);
		private final EnumLiteralDeclaration cNavy_BlueEnumLiteralDeclaration_78 = (EnumLiteralDeclaration)cAlternatives.eContents().get(78);
		private final Keyword cNavy_BlueNavy_BlueKeyword_78_0 = (Keyword)cNavy_BlueEnumLiteralDeclaration_78.eContents().get(0);
		private final EnumLiteralDeclaration cNeon_BlueEnumLiteralDeclaration_79 = (EnumLiteralDeclaration)cAlternatives.eContents().get(79);
		private final Keyword cNeon_BlueNeon_BlueKeyword_79_0 = (Keyword)cNeon_BlueEnumLiteralDeclaration_79.eContents().get(0);
		private final EnumLiteralDeclaration cNeon_PinkEnumLiteralDeclaration_80 = (EnumLiteralDeclaration)cAlternatives.eContents().get(80);
		private final Keyword cNeon_PinkNeon_PinkKeyword_80_0 = (Keyword)cNeon_PinkEnumLiteralDeclaration_80.eContents().get(0);
		private final EnumLiteralDeclaration cNew_Midnight_BlueEnumLiteralDeclaration_81 = (EnumLiteralDeclaration)cAlternatives.eContents().get(81);
		private final Keyword cNew_Midnight_BlueNew_Midnight_BlueKeyword_81_0 = (Keyword)cNew_Midnight_BlueEnumLiteralDeclaration_81.eContents().get(0);
		private final EnumLiteralDeclaration cNew_TanEnumLiteralDeclaration_82 = (EnumLiteralDeclaration)cAlternatives.eContents().get(82);
		private final Keyword cNew_TanNew_TanKeyword_82_0 = (Keyword)cNew_TanEnumLiteralDeclaration_82.eContents().get(0);
		private final EnumLiteralDeclaration cOld_GoldEnumLiteralDeclaration_83 = (EnumLiteralDeclaration)cAlternatives.eContents().get(83);
		private final Keyword cOld_GoldOld_GoldKeyword_83_0 = (Keyword)cOld_GoldEnumLiteralDeclaration_83.eContents().get(0);
		private final EnumLiteralDeclaration cOrange_RedEnumLiteralDeclaration_84 = (EnumLiteralDeclaration)cAlternatives.eContents().get(84);
		private final Keyword cOrange_RedOrange_RedKeyword_84_0 = (Keyword)cOrange_RedEnumLiteralDeclaration_84.eContents().get(0);
		private final EnumLiteralDeclaration cOrchidEnumLiteralDeclaration_85 = (EnumLiteralDeclaration)cAlternatives.eContents().get(85);
		private final Keyword cOrchidOrchidKeyword_85_0 = (Keyword)cOrchidEnumLiteralDeclaration_85.eContents().get(0);
		private final EnumLiteralDeclaration cPale_GreenEnumLiteralDeclaration_86 = (EnumLiteralDeclaration)cAlternatives.eContents().get(86);
		private final Keyword cPale_GreenPale_GreenKeyword_86_0 = (Keyword)cPale_GreenEnumLiteralDeclaration_86.eContents().get(0);
		private final EnumLiteralDeclaration cPlumEnumLiteralDeclaration_87 = (EnumLiteralDeclaration)cAlternatives.eContents().get(87);
		private final Keyword cPlumPlumKeyword_87_0 = (Keyword)cPlumEnumLiteralDeclaration_87.eContents().get(0);
		private final EnumLiteralDeclaration cQuartzEnumLiteralDeclaration_88 = (EnumLiteralDeclaration)cAlternatives.eContents().get(88);
		private final Keyword cQuartzQuartzKeyword_88_0 = (Keyword)cQuartzEnumLiteralDeclaration_88.eContents().get(0);
		private final EnumLiteralDeclaration cRich_BlueEnumLiteralDeclaration_89 = (EnumLiteralDeclaration)cAlternatives.eContents().get(89);
		private final Keyword cRich_BlueRich_BlueKeyword_89_0 = (Keyword)cRich_BlueEnumLiteralDeclaration_89.eContents().get(0);
		private final EnumLiteralDeclaration cScarletEnumLiteralDeclaration_90 = (EnumLiteralDeclaration)cAlternatives.eContents().get(90);
		private final Keyword cScarletScarletKeyword_90_0 = (Keyword)cScarletEnumLiteralDeclaration_90.eContents().get(0);
		private final EnumLiteralDeclaration cSea_GreenEnumLiteralDeclaration_91 = (EnumLiteralDeclaration)cAlternatives.eContents().get(91);
		private final Keyword cSea_GreenSea_GreenKeyword_91_0 = (Keyword)cSea_GreenEnumLiteralDeclaration_91.eContents().get(0);
		private final EnumLiteralDeclaration cSemi_Sweet_ChocolateEnumLiteralDeclaration_92 = (EnumLiteralDeclaration)cAlternatives.eContents().get(92);
		private final Keyword cSemi_Sweet_ChocolateSemi_Sweet_ChocolateKeyword_92_0 = (Keyword)cSemi_Sweet_ChocolateEnumLiteralDeclaration_92.eContents().get(0);
		private final EnumLiteralDeclaration cSky_BlueEnumLiteralDeclaration_93 = (EnumLiteralDeclaration)cAlternatives.eContents().get(93);
		private final Keyword cSky_BlueSky_BlueKeyword_93_0 = (Keyword)cSky_BlueEnumLiteralDeclaration_93.eContents().get(0);
		private final EnumLiteralDeclaration cSlate_BlueEnumLiteralDeclaration_94 = (EnumLiteralDeclaration)cAlternatives.eContents().get(94);
		private final Keyword cSlate_BlueSlate_BlueKeyword_94_0 = (Keyword)cSlate_BlueEnumLiteralDeclaration_94.eContents().get(0);
		private final EnumLiteralDeclaration cSpicy_PinkEnumLiteralDeclaration_95 = (EnumLiteralDeclaration)cAlternatives.eContents().get(95);
		private final Keyword cSpicy_PinkSpicy_PinkKeyword_95_0 = (Keyword)cSpicy_PinkEnumLiteralDeclaration_95.eContents().get(0);
		private final EnumLiteralDeclaration cSpring_GreenEnumLiteralDeclaration_96 = (EnumLiteralDeclaration)cAlternatives.eContents().get(96);
		private final Keyword cSpring_GreenSpring_GreenKeyword_96_0 = (Keyword)cSpring_GreenEnumLiteralDeclaration_96.eContents().get(0);
		private final EnumLiteralDeclaration cSteel_BlueEnumLiteralDeclaration_97 = (EnumLiteralDeclaration)cAlternatives.eContents().get(97);
		private final Keyword cSteel_BlueSteel_BlueKeyword_97_0 = (Keyword)cSteel_BlueEnumLiteralDeclaration_97.eContents().get(0);
		
		//enum FMFFidColorEnum:
		//	Aquamarine // "Aquamarine"
		//	// "Baker's Chocolate"
		//	// "Black"
		//	// "Blue"
		//	// "Brass"
		//	// "Bright Gold"
		//	// "Brown"
		//	// "Bronze"
		//	// "Gold"
		//	// "Grey"
		//	// "Green"
		//	// "Copper"
		//	// "Coral"
		//	// "Cyan"
		//	// "Dark Green"
		//	// "Green Yellow"
		//	// "Magenta"
		//	// "Maroon"
		//	// "Medium Blue"
		//	// "Sienna"
		//	// "Silver"
		//	// "Salmon"
		//	// "Orange"
		//	// "Pink"
		//	// "Red"
		//	// "Summer Sky"
		//	// "Tan"
		//	// "Thistle"
		//	// "Turquoise"
		//	// "Very Dark Brown"
		//	// "Very Light Grey"
		//	// "Violet"
		//	// "Violet Red"
		//	// "Wheat"
		//	// "White"
		//	// "Yellow"
		//	// "Yellow Green"
		//	// "Dark Yellow"
		//	// "Bronze II"
		//	// "Cadet Blue"
		//	// "Cool Copper"
		//	// "Corn Flower Blue"
		//	// "Dark Brown"
		//	// "Dark Green Copper"
		//	// "Dark Olive Green"
		//	// "Dark Orchid"
		//	// "Dark Purple"
		//	// "Dark Slate Blue"
		//	// "Dark Turquoise"
		//	// "Dark Tan"
		//	// "Dark Wood"
		//	// "Dim Grey"
		//	// "Dusty Rose"
		//	// "Feldspar"
		//	// "Firebrick"
		//	// "Forest Green"
		//	// "Goldenrod"
		//	// "Green Copper"
		//	// "Hunter Green"
		//	// "Indian Red"
		//	// "Khaki"
		//	// "Light Blue"
		//	// "Light Grey"
		//	// "Light Steel Blue"
		//	// "Light Wood"
		//	// "Lime Green"
		//	// "Mandarian Orange"
		//	// "Medium Aquamarine"
		//	// "Medium Forest Green"
		//	// "Medium Goldenrod"
		//	// "Medium Orchid"
		//	// "Medium Sea Green"
		//	// "Medium Slate Blue"
		//	// "Medium Spring Green"
		//	// "Medium Turquoise"
		//	// "Medium Violet Red"
		//	// "Medium Wood"
		//	// "Midnight Blue"
		//	// "Navy Blue"
		//	// "Neon Blue"
		//	// "Neon Pink"
		//	// "New Midnight Blue"
		//	// ""
		//	// "Old Gold"
		//	// "Orange Red"
		//	// "Orchid"
		//	// "Pale Green"
		//	// "Plum"
		//	// "Quartz"
		//	// "Rich Blue"
		//	// "Scarlet"
		//	// "Sea Green"
		//	// "Semi-Sweet Chocolate"
		//	// "Sky Blue"
		//	// "Slate Blue"
		//	// "Spicy Pink"
		//	// "Spring Green"
		//	| Bakers_Chocolate | Black | Blue | Brass | Bright_Gold | Brown | Bronze | Gold | Grey | Green | Copper | Coral | Cyan
		//	| Dark_Green | Green_Yellow | Magenta | Maroon | Medium_Blue | Sienna | Silver | Salmon | Orange | Pink | Red |
		//	Summer_Sky | Tan | Thistle | Turquoise | Very_Dark_Brown | Very_Light_Grey | Violet | Violet_Red | Wheat | White |
		//	Yellow | Yellow_Green | Dark_Yellow | Bronze_II | Cadet_Blue | Cool_Copper | Corn_Flower_Blue | Dark_Brown |
		//	Dark_Green_Copper | Dark_Olive_Green | Dark_Orchid | Dark_Purple | Dark_Slate_Blue | Dark_Turquoise | Dark_Tan |
		//	Dark_Wood | Dim_Grey | Dusty_Rose | Feldspar | Firebrick | Forest_Green | Goldenrod | Green_Copper | Hunter_Green |
		//	Indian_Red | Khaki | Light_Blue | Light_Grey | Light_Steel_Blue | Light_Wood | Lime_Green | Mandarian_Orange |
		//	Medium_Aquamarine | Medium_Forest_Green | Medium_Goldenrod | Medium_Orchid | Medium_Sea_Green | Medium_Slate_Blue |
		//	Medium_Spring_Green | Medium_Turquoise | Medium_Violet_Red | Medium_Wood | Midnight_Blue | Navy_Blue | Neon_Blue |
		//	Neon_Pink | New_Midnight_Blue | New_Tan | Old_Gold | Orange_Red | Orchid | Pale_Green | Plum | Quartz | Rich_Blue |
		//	Scarlet | Sea_Green | Semi_Sweet_Chocolate | Sky_Blue | Slate_Blue | Spicy_Pink | Spring_Green | // "Steel Blue"
		//	Steel_Blue;
		public EnumRule getRule() { return rule; }

		//Aquamarine // "Aquamarine"
		//// "Baker's Chocolate"
		//// "Black"
		//// "Blue"
		//// "Brass"
		//// "Bright Gold"
		//// "Brown"
		//// "Bronze"
		//// "Gold"
		//// "Grey"
		//// "Green"
		//// "Copper"
		//// "Coral"
		//// "Cyan"
		//// "Dark Green"
		//// "Green Yellow"
		//// "Magenta"
		//// "Maroon"
		//// "Medium Blue"
		//// "Sienna"
		//// "Silver"
		//// "Salmon"
		//// "Orange"
		//// "Pink"
		//// "Red"
		//// "Summer Sky"
		//// "Tan"
		//// "Thistle"
		//// "Turquoise"
		//// "Very Dark Brown"
		//// "Very Light Grey"
		//// "Violet"
		//// "Violet Red"
		//// "Wheat"
		//// "White"
		//// "Yellow"
		//// "Yellow Green"
		//// "Dark Yellow"
		//// "Bronze II"
		//// "Cadet Blue"
		//// "Cool Copper"
		//// "Corn Flower Blue"
		//// "Dark Brown"
		//// "Dark Green Copper"
		//// "Dark Olive Green"
		//// "Dark Orchid"
		//// "Dark Purple"
		//// "Dark Slate Blue"
		//// "Dark Turquoise"
		//// "Dark Tan"
		//// "Dark Wood"
		//// "Dim Grey"
		//// "Dusty Rose"
		//// "Feldspar"
		//// "Firebrick"
		//// "Forest Green"
		//// "Goldenrod"
		//// "Green Copper"
		//// "Hunter Green"
		//// "Indian Red"
		//// "Khaki"
		//// "Light Blue"
		//// "Light Grey"
		//// "Light Steel Blue"
		//// "Light Wood"
		//// "Lime Green"
		//// "Mandarian Orange"
		//// "Medium Aquamarine"
		//// "Medium Forest Green"
		//// "Medium Goldenrod"
		//// "Medium Orchid"
		//// "Medium Sea Green"
		//// "Medium Slate Blue"
		//// "Medium Spring Green"
		//// "Medium Turquoise"
		//// "Medium Violet Red"
		//// "Medium Wood"
		//// "Midnight Blue"
		//// "Navy Blue"
		//// "Neon Blue"
		//// "Neon Pink"
		//// "New Midnight Blue"
		//// ""
		//// "Old Gold"
		//// "Orange Red"
		//// "Orchid"
		//// "Pale Green"
		//// "Plum"
		//// "Quartz"
		//// "Rich Blue"
		//// "Scarlet"
		//// "Sea Green"
		//// "Semi-Sweet Chocolate"
		//// "Sky Blue"
		//// "Slate Blue"
		//// "Spicy Pink"
		//// "Spring Green"
		//| Bakers_Chocolate | Black | Blue | Brass | Bright_Gold | Brown | Bronze | Gold | Grey | Green | Copper | Coral | Cyan |
		//Dark_Green | Green_Yellow | Magenta | Maroon | Medium_Blue | Sienna | Silver | Salmon | Orange | Pink | Red |
		//Summer_Sky | Tan | Thistle | Turquoise | Very_Dark_Brown | Very_Light_Grey | Violet | Violet_Red | Wheat | White |
		//Yellow | Yellow_Green | Dark_Yellow | Bronze_II | Cadet_Blue | Cool_Copper | Corn_Flower_Blue | Dark_Brown |
		//Dark_Green_Copper | Dark_Olive_Green | Dark_Orchid | Dark_Purple | Dark_Slate_Blue | Dark_Turquoise | Dark_Tan |
		//Dark_Wood | Dim_Grey | Dusty_Rose | Feldspar | Firebrick | Forest_Green | Goldenrod | Green_Copper | Hunter_Green |
		//Indian_Red | Khaki | Light_Blue | Light_Grey | Light_Steel_Blue | Light_Wood | Lime_Green | Mandarian_Orange |
		//Medium_Aquamarine | Medium_Forest_Green | Medium_Goldenrod | Medium_Orchid | Medium_Sea_Green | Medium_Slate_Blue |
		//Medium_Spring_Green | Medium_Turquoise | Medium_Violet_Red | Medium_Wood | Midnight_Blue | Navy_Blue | Neon_Blue |
		//Neon_Pink | New_Midnight_Blue | New_Tan | Old_Gold | Orange_Red | Orchid | Pale_Green | Plum | Quartz | Rich_Blue |
		//Scarlet | Sea_Green | Semi_Sweet_Chocolate | Sky_Blue | Slate_Blue | Spicy_Pink | Spring_Green | // "Steel Blue"
		//Steel_Blue
		public Alternatives getAlternatives() { return cAlternatives; }

		//Aquamarine
		public EnumLiteralDeclaration getAquamarineEnumLiteralDeclaration_0() { return cAquamarineEnumLiteralDeclaration_0; }

		//"Aquamarine"
		public Keyword getAquamarineAquamarineKeyword_0_0() { return cAquamarineAquamarineKeyword_0_0; }

		//Bakers_Chocolate
		public EnumLiteralDeclaration getBakers_ChocolateEnumLiteralDeclaration_1() { return cBakers_ChocolateEnumLiteralDeclaration_1; }

		//"Bakers_Chocolate"
		public Keyword getBakers_ChocolateBakers_ChocolateKeyword_1_0() { return cBakers_ChocolateBakers_ChocolateKeyword_1_0; }

		//Black
		public EnumLiteralDeclaration getBlackEnumLiteralDeclaration_2() { return cBlackEnumLiteralDeclaration_2; }

		//"Black"
		public Keyword getBlackBlackKeyword_2_0() { return cBlackBlackKeyword_2_0; }

		//Blue
		public EnumLiteralDeclaration getBlueEnumLiteralDeclaration_3() { return cBlueEnumLiteralDeclaration_3; }

		//"Blue"
		public Keyword getBlueBlueKeyword_3_0() { return cBlueBlueKeyword_3_0; }

		//Brass
		public EnumLiteralDeclaration getBrassEnumLiteralDeclaration_4() { return cBrassEnumLiteralDeclaration_4; }

		//"Brass"
		public Keyword getBrassBrassKeyword_4_0() { return cBrassBrassKeyword_4_0; }

		//Bright_Gold
		public EnumLiteralDeclaration getBright_GoldEnumLiteralDeclaration_5() { return cBright_GoldEnumLiteralDeclaration_5; }

		//"Bright_Gold"
		public Keyword getBright_GoldBright_GoldKeyword_5_0() { return cBright_GoldBright_GoldKeyword_5_0; }

		//Brown
		public EnumLiteralDeclaration getBrownEnumLiteralDeclaration_6() { return cBrownEnumLiteralDeclaration_6; }

		//"Brown"
		public Keyword getBrownBrownKeyword_6_0() { return cBrownBrownKeyword_6_0; }

		//Bronze
		public EnumLiteralDeclaration getBronzeEnumLiteralDeclaration_7() { return cBronzeEnumLiteralDeclaration_7; }

		//"Bronze"
		public Keyword getBronzeBronzeKeyword_7_0() { return cBronzeBronzeKeyword_7_0; }

		//Gold
		public EnumLiteralDeclaration getGoldEnumLiteralDeclaration_8() { return cGoldEnumLiteralDeclaration_8; }

		//"Gold"
		public Keyword getGoldGoldKeyword_8_0() { return cGoldGoldKeyword_8_0; }

		//Grey
		public EnumLiteralDeclaration getGreyEnumLiteralDeclaration_9() { return cGreyEnumLiteralDeclaration_9; }

		//"Grey"
		public Keyword getGreyGreyKeyword_9_0() { return cGreyGreyKeyword_9_0; }

		//Green
		public EnumLiteralDeclaration getGreenEnumLiteralDeclaration_10() { return cGreenEnumLiteralDeclaration_10; }

		//"Green"
		public Keyword getGreenGreenKeyword_10_0() { return cGreenGreenKeyword_10_0; }

		//Copper
		public EnumLiteralDeclaration getCopperEnumLiteralDeclaration_11() { return cCopperEnumLiteralDeclaration_11; }

		//"Copper"
		public Keyword getCopperCopperKeyword_11_0() { return cCopperCopperKeyword_11_0; }

		//Coral
		public EnumLiteralDeclaration getCoralEnumLiteralDeclaration_12() { return cCoralEnumLiteralDeclaration_12; }

		//"Coral"
		public Keyword getCoralCoralKeyword_12_0() { return cCoralCoralKeyword_12_0; }

		//Cyan
		public EnumLiteralDeclaration getCyanEnumLiteralDeclaration_13() { return cCyanEnumLiteralDeclaration_13; }

		//"Cyan"
		public Keyword getCyanCyanKeyword_13_0() { return cCyanCyanKeyword_13_0; }

		//Dark_Green
		public EnumLiteralDeclaration getDark_GreenEnumLiteralDeclaration_14() { return cDark_GreenEnumLiteralDeclaration_14; }

		//"Dark_Green"
		public Keyword getDark_GreenDark_GreenKeyword_14_0() { return cDark_GreenDark_GreenKeyword_14_0; }

		//Green_Yellow
		public EnumLiteralDeclaration getGreen_YellowEnumLiteralDeclaration_15() { return cGreen_YellowEnumLiteralDeclaration_15; }

		//"Green_Yellow"
		public Keyword getGreen_YellowGreen_YellowKeyword_15_0() { return cGreen_YellowGreen_YellowKeyword_15_0; }

		//Magenta
		public EnumLiteralDeclaration getMagentaEnumLiteralDeclaration_16() { return cMagentaEnumLiteralDeclaration_16; }

		//"Magenta"
		public Keyword getMagentaMagentaKeyword_16_0() { return cMagentaMagentaKeyword_16_0; }

		//Maroon
		public EnumLiteralDeclaration getMaroonEnumLiteralDeclaration_17() { return cMaroonEnumLiteralDeclaration_17; }

		//"Maroon"
		public Keyword getMaroonMaroonKeyword_17_0() { return cMaroonMaroonKeyword_17_0; }

		//Medium_Blue
		public EnumLiteralDeclaration getMedium_BlueEnumLiteralDeclaration_18() { return cMedium_BlueEnumLiteralDeclaration_18; }

		//"Medium_Blue"
		public Keyword getMedium_BlueMedium_BlueKeyword_18_0() { return cMedium_BlueMedium_BlueKeyword_18_0; }

		//Sienna
		public EnumLiteralDeclaration getSiennaEnumLiteralDeclaration_19() { return cSiennaEnumLiteralDeclaration_19; }

		//"Sienna"
		public Keyword getSiennaSiennaKeyword_19_0() { return cSiennaSiennaKeyword_19_0; }

		//Silver
		public EnumLiteralDeclaration getSilverEnumLiteralDeclaration_20() { return cSilverEnumLiteralDeclaration_20; }

		//"Silver"
		public Keyword getSilverSilverKeyword_20_0() { return cSilverSilverKeyword_20_0; }

		//Salmon
		public EnumLiteralDeclaration getSalmonEnumLiteralDeclaration_21() { return cSalmonEnumLiteralDeclaration_21; }

		//"Salmon"
		public Keyword getSalmonSalmonKeyword_21_0() { return cSalmonSalmonKeyword_21_0; }

		//Orange
		public EnumLiteralDeclaration getOrangeEnumLiteralDeclaration_22() { return cOrangeEnumLiteralDeclaration_22; }

		//"Orange"
		public Keyword getOrangeOrangeKeyword_22_0() { return cOrangeOrangeKeyword_22_0; }

		//Pink
		public EnumLiteralDeclaration getPinkEnumLiteralDeclaration_23() { return cPinkEnumLiteralDeclaration_23; }

		//"Pink"
		public Keyword getPinkPinkKeyword_23_0() { return cPinkPinkKeyword_23_0; }

		//Red
		public EnumLiteralDeclaration getRedEnumLiteralDeclaration_24() { return cRedEnumLiteralDeclaration_24; }

		//"Red"
		public Keyword getRedRedKeyword_24_0() { return cRedRedKeyword_24_0; }

		//Summer_Sky
		public EnumLiteralDeclaration getSummer_SkyEnumLiteralDeclaration_25() { return cSummer_SkyEnumLiteralDeclaration_25; }

		//"Summer_Sky"
		public Keyword getSummer_SkySummer_SkyKeyword_25_0() { return cSummer_SkySummer_SkyKeyword_25_0; }

		//Tan
		public EnumLiteralDeclaration getTanEnumLiteralDeclaration_26() { return cTanEnumLiteralDeclaration_26; }

		//"Tan"
		public Keyword getTanTanKeyword_26_0() { return cTanTanKeyword_26_0; }

		//Thistle
		public EnumLiteralDeclaration getThistleEnumLiteralDeclaration_27() { return cThistleEnumLiteralDeclaration_27; }

		//"Thistle"
		public Keyword getThistleThistleKeyword_27_0() { return cThistleThistleKeyword_27_0; }

		//Turquoise
		public EnumLiteralDeclaration getTurquoiseEnumLiteralDeclaration_28() { return cTurquoiseEnumLiteralDeclaration_28; }

		//"Turquoise"
		public Keyword getTurquoiseTurquoiseKeyword_28_0() { return cTurquoiseTurquoiseKeyword_28_0; }

		//Very_Dark_Brown
		public EnumLiteralDeclaration getVery_Dark_BrownEnumLiteralDeclaration_29() { return cVery_Dark_BrownEnumLiteralDeclaration_29; }

		//"Very_Dark_Brown"
		public Keyword getVery_Dark_BrownVery_Dark_BrownKeyword_29_0() { return cVery_Dark_BrownVery_Dark_BrownKeyword_29_0; }

		//Very_Light_Grey
		public EnumLiteralDeclaration getVery_Light_GreyEnumLiteralDeclaration_30() { return cVery_Light_GreyEnumLiteralDeclaration_30; }

		//"Very_Light_Grey"
		public Keyword getVery_Light_GreyVery_Light_GreyKeyword_30_0() { return cVery_Light_GreyVery_Light_GreyKeyword_30_0; }

		//Violet
		public EnumLiteralDeclaration getVioletEnumLiteralDeclaration_31() { return cVioletEnumLiteralDeclaration_31; }

		//"Violet"
		public Keyword getVioletVioletKeyword_31_0() { return cVioletVioletKeyword_31_0; }

		//Violet_Red
		public EnumLiteralDeclaration getViolet_RedEnumLiteralDeclaration_32() { return cViolet_RedEnumLiteralDeclaration_32; }

		//"Violet_Red"
		public Keyword getViolet_RedViolet_RedKeyword_32_0() { return cViolet_RedViolet_RedKeyword_32_0; }

		//Wheat
		public EnumLiteralDeclaration getWheatEnumLiteralDeclaration_33() { return cWheatEnumLiteralDeclaration_33; }

		//"Wheat"
		public Keyword getWheatWheatKeyword_33_0() { return cWheatWheatKeyword_33_0; }

		//White
		public EnumLiteralDeclaration getWhiteEnumLiteralDeclaration_34() { return cWhiteEnumLiteralDeclaration_34; }

		//"White"
		public Keyword getWhiteWhiteKeyword_34_0() { return cWhiteWhiteKeyword_34_0; }

		//Yellow
		public EnumLiteralDeclaration getYellowEnumLiteralDeclaration_35() { return cYellowEnumLiteralDeclaration_35; }

		//"Yellow"
		public Keyword getYellowYellowKeyword_35_0() { return cYellowYellowKeyword_35_0; }

		//Yellow_Green
		public EnumLiteralDeclaration getYellow_GreenEnumLiteralDeclaration_36() { return cYellow_GreenEnumLiteralDeclaration_36; }

		//"Yellow_Green"
		public Keyword getYellow_GreenYellow_GreenKeyword_36_0() { return cYellow_GreenYellow_GreenKeyword_36_0; }

		//Dark_Yellow
		public EnumLiteralDeclaration getDark_YellowEnumLiteralDeclaration_37() { return cDark_YellowEnumLiteralDeclaration_37; }

		//"Dark_Yellow"
		public Keyword getDark_YellowDark_YellowKeyword_37_0() { return cDark_YellowDark_YellowKeyword_37_0; }

		//Bronze_II
		public EnumLiteralDeclaration getBronze_IIEnumLiteralDeclaration_38() { return cBronze_IIEnumLiteralDeclaration_38; }

		//"Bronze_II"
		public Keyword getBronze_IIBronze_IIKeyword_38_0() { return cBronze_IIBronze_IIKeyword_38_0; }

		//Cadet_Blue
		public EnumLiteralDeclaration getCadet_BlueEnumLiteralDeclaration_39() { return cCadet_BlueEnumLiteralDeclaration_39; }

		//"Cadet_Blue"
		public Keyword getCadet_BlueCadet_BlueKeyword_39_0() { return cCadet_BlueCadet_BlueKeyword_39_0; }

		//Cool_Copper
		public EnumLiteralDeclaration getCool_CopperEnumLiteralDeclaration_40() { return cCool_CopperEnumLiteralDeclaration_40; }

		//"Cool_Copper"
		public Keyword getCool_CopperCool_CopperKeyword_40_0() { return cCool_CopperCool_CopperKeyword_40_0; }

		//Corn_Flower_Blue
		public EnumLiteralDeclaration getCorn_Flower_BlueEnumLiteralDeclaration_41() { return cCorn_Flower_BlueEnumLiteralDeclaration_41; }

		//"Corn_Flower_Blue"
		public Keyword getCorn_Flower_BlueCorn_Flower_BlueKeyword_41_0() { return cCorn_Flower_BlueCorn_Flower_BlueKeyword_41_0; }

		//Dark_Brown
		public EnumLiteralDeclaration getDark_BrownEnumLiteralDeclaration_42() { return cDark_BrownEnumLiteralDeclaration_42; }

		//"Dark_Brown"
		public Keyword getDark_BrownDark_BrownKeyword_42_0() { return cDark_BrownDark_BrownKeyword_42_0; }

		//Dark_Green_Copper
		public EnumLiteralDeclaration getDark_Green_CopperEnumLiteralDeclaration_43() { return cDark_Green_CopperEnumLiteralDeclaration_43; }

		//"Dark_Green_Copper"
		public Keyword getDark_Green_CopperDark_Green_CopperKeyword_43_0() { return cDark_Green_CopperDark_Green_CopperKeyword_43_0; }

		//Dark_Olive_Green
		public EnumLiteralDeclaration getDark_Olive_GreenEnumLiteralDeclaration_44() { return cDark_Olive_GreenEnumLiteralDeclaration_44; }

		//"Dark_Olive_Green"
		public Keyword getDark_Olive_GreenDark_Olive_GreenKeyword_44_0() { return cDark_Olive_GreenDark_Olive_GreenKeyword_44_0; }

		//Dark_Orchid
		public EnumLiteralDeclaration getDark_OrchidEnumLiteralDeclaration_45() { return cDark_OrchidEnumLiteralDeclaration_45; }

		//"Dark_Orchid"
		public Keyword getDark_OrchidDark_OrchidKeyword_45_0() { return cDark_OrchidDark_OrchidKeyword_45_0; }

		//Dark_Purple
		public EnumLiteralDeclaration getDark_PurpleEnumLiteralDeclaration_46() { return cDark_PurpleEnumLiteralDeclaration_46; }

		//"Dark_Purple"
		public Keyword getDark_PurpleDark_PurpleKeyword_46_0() { return cDark_PurpleDark_PurpleKeyword_46_0; }

		//Dark_Slate_Blue
		public EnumLiteralDeclaration getDark_Slate_BlueEnumLiteralDeclaration_47() { return cDark_Slate_BlueEnumLiteralDeclaration_47; }

		//"Dark_Slate_Blue"
		public Keyword getDark_Slate_BlueDark_Slate_BlueKeyword_47_0() { return cDark_Slate_BlueDark_Slate_BlueKeyword_47_0; }

		//Dark_Turquoise
		public EnumLiteralDeclaration getDark_TurquoiseEnumLiteralDeclaration_48() { return cDark_TurquoiseEnumLiteralDeclaration_48; }

		//"Dark_Turquoise"
		public Keyword getDark_TurquoiseDark_TurquoiseKeyword_48_0() { return cDark_TurquoiseDark_TurquoiseKeyword_48_0; }

		//Dark_Tan
		public EnumLiteralDeclaration getDark_TanEnumLiteralDeclaration_49() { return cDark_TanEnumLiteralDeclaration_49; }

		//"Dark_Tan"
		public Keyword getDark_TanDark_TanKeyword_49_0() { return cDark_TanDark_TanKeyword_49_0; }

		//Dark_Wood
		public EnumLiteralDeclaration getDark_WoodEnumLiteralDeclaration_50() { return cDark_WoodEnumLiteralDeclaration_50; }

		//"Dark_Wood"
		public Keyword getDark_WoodDark_WoodKeyword_50_0() { return cDark_WoodDark_WoodKeyword_50_0; }

		//Dim_Grey
		public EnumLiteralDeclaration getDim_GreyEnumLiteralDeclaration_51() { return cDim_GreyEnumLiteralDeclaration_51; }

		//"Dim_Grey"
		public Keyword getDim_GreyDim_GreyKeyword_51_0() { return cDim_GreyDim_GreyKeyword_51_0; }

		//Dusty_Rose
		public EnumLiteralDeclaration getDusty_RoseEnumLiteralDeclaration_52() { return cDusty_RoseEnumLiteralDeclaration_52; }

		//"Dusty_Rose"
		public Keyword getDusty_RoseDusty_RoseKeyword_52_0() { return cDusty_RoseDusty_RoseKeyword_52_0; }

		//Feldspar
		public EnumLiteralDeclaration getFeldsparEnumLiteralDeclaration_53() { return cFeldsparEnumLiteralDeclaration_53; }

		//"Feldspar"
		public Keyword getFeldsparFeldsparKeyword_53_0() { return cFeldsparFeldsparKeyword_53_0; }

		//Firebrick
		public EnumLiteralDeclaration getFirebrickEnumLiteralDeclaration_54() { return cFirebrickEnumLiteralDeclaration_54; }

		//"Firebrick"
		public Keyword getFirebrickFirebrickKeyword_54_0() { return cFirebrickFirebrickKeyword_54_0; }

		//Forest_Green
		public EnumLiteralDeclaration getForest_GreenEnumLiteralDeclaration_55() { return cForest_GreenEnumLiteralDeclaration_55; }

		//"Forest_Green"
		public Keyword getForest_GreenForest_GreenKeyword_55_0() { return cForest_GreenForest_GreenKeyword_55_0; }

		//Goldenrod
		public EnumLiteralDeclaration getGoldenrodEnumLiteralDeclaration_56() { return cGoldenrodEnumLiteralDeclaration_56; }

		//"Goldenrod"
		public Keyword getGoldenrodGoldenrodKeyword_56_0() { return cGoldenrodGoldenrodKeyword_56_0; }

		//Green_Copper
		public EnumLiteralDeclaration getGreen_CopperEnumLiteralDeclaration_57() { return cGreen_CopperEnumLiteralDeclaration_57; }

		//"Green_Copper"
		public Keyword getGreen_CopperGreen_CopperKeyword_57_0() { return cGreen_CopperGreen_CopperKeyword_57_0; }

		//Hunter_Green
		public EnumLiteralDeclaration getHunter_GreenEnumLiteralDeclaration_58() { return cHunter_GreenEnumLiteralDeclaration_58; }

		//"Hunter_Green"
		public Keyword getHunter_GreenHunter_GreenKeyword_58_0() { return cHunter_GreenHunter_GreenKeyword_58_0; }

		//Indian_Red
		public EnumLiteralDeclaration getIndian_RedEnumLiteralDeclaration_59() { return cIndian_RedEnumLiteralDeclaration_59; }

		//"Indian_Red"
		public Keyword getIndian_RedIndian_RedKeyword_59_0() { return cIndian_RedIndian_RedKeyword_59_0; }

		//Khaki
		public EnumLiteralDeclaration getKhakiEnumLiteralDeclaration_60() { return cKhakiEnumLiteralDeclaration_60; }

		//"Khaki"
		public Keyword getKhakiKhakiKeyword_60_0() { return cKhakiKhakiKeyword_60_0; }

		//Light_Blue
		public EnumLiteralDeclaration getLight_BlueEnumLiteralDeclaration_61() { return cLight_BlueEnumLiteralDeclaration_61; }

		//"Light_Blue"
		public Keyword getLight_BlueLight_BlueKeyword_61_0() { return cLight_BlueLight_BlueKeyword_61_0; }

		//Light_Grey
		public EnumLiteralDeclaration getLight_GreyEnumLiteralDeclaration_62() { return cLight_GreyEnumLiteralDeclaration_62; }

		//"Light_Grey"
		public Keyword getLight_GreyLight_GreyKeyword_62_0() { return cLight_GreyLight_GreyKeyword_62_0; }

		//Light_Steel_Blue
		public EnumLiteralDeclaration getLight_Steel_BlueEnumLiteralDeclaration_63() { return cLight_Steel_BlueEnumLiteralDeclaration_63; }

		//"Light_Steel_Blue"
		public Keyword getLight_Steel_BlueLight_Steel_BlueKeyword_63_0() { return cLight_Steel_BlueLight_Steel_BlueKeyword_63_0; }

		//Light_Wood
		public EnumLiteralDeclaration getLight_WoodEnumLiteralDeclaration_64() { return cLight_WoodEnumLiteralDeclaration_64; }

		//"Light_Wood"
		public Keyword getLight_WoodLight_WoodKeyword_64_0() { return cLight_WoodLight_WoodKeyword_64_0; }

		//Lime_Green
		public EnumLiteralDeclaration getLime_GreenEnumLiteralDeclaration_65() { return cLime_GreenEnumLiteralDeclaration_65; }

		//"Lime_Green"
		public Keyword getLime_GreenLime_GreenKeyword_65_0() { return cLime_GreenLime_GreenKeyword_65_0; }

		//Mandarian_Orange
		public EnumLiteralDeclaration getMandarian_OrangeEnumLiteralDeclaration_66() { return cMandarian_OrangeEnumLiteralDeclaration_66; }

		//"Mandarian_Orange"
		public Keyword getMandarian_OrangeMandarian_OrangeKeyword_66_0() { return cMandarian_OrangeMandarian_OrangeKeyword_66_0; }

		//Medium_Aquamarine
		public EnumLiteralDeclaration getMedium_AquamarineEnumLiteralDeclaration_67() { return cMedium_AquamarineEnumLiteralDeclaration_67; }

		//"Medium_Aquamarine"
		public Keyword getMedium_AquamarineMedium_AquamarineKeyword_67_0() { return cMedium_AquamarineMedium_AquamarineKeyword_67_0; }

		//Medium_Forest_Green
		public EnumLiteralDeclaration getMedium_Forest_GreenEnumLiteralDeclaration_68() { return cMedium_Forest_GreenEnumLiteralDeclaration_68; }

		//"Medium_Forest_Green"
		public Keyword getMedium_Forest_GreenMedium_Forest_GreenKeyword_68_0() { return cMedium_Forest_GreenMedium_Forest_GreenKeyword_68_0; }

		//Medium_Goldenrod
		public EnumLiteralDeclaration getMedium_GoldenrodEnumLiteralDeclaration_69() { return cMedium_GoldenrodEnumLiteralDeclaration_69; }

		//"Medium_Goldenrod"
		public Keyword getMedium_GoldenrodMedium_GoldenrodKeyword_69_0() { return cMedium_GoldenrodMedium_GoldenrodKeyword_69_0; }

		//Medium_Orchid
		public EnumLiteralDeclaration getMedium_OrchidEnumLiteralDeclaration_70() { return cMedium_OrchidEnumLiteralDeclaration_70; }

		//"Medium_Orchid"
		public Keyword getMedium_OrchidMedium_OrchidKeyword_70_0() { return cMedium_OrchidMedium_OrchidKeyword_70_0; }

		//Medium_Sea_Green
		public EnumLiteralDeclaration getMedium_Sea_GreenEnumLiteralDeclaration_71() { return cMedium_Sea_GreenEnumLiteralDeclaration_71; }

		//"Medium_Sea_Green"
		public Keyword getMedium_Sea_GreenMedium_Sea_GreenKeyword_71_0() { return cMedium_Sea_GreenMedium_Sea_GreenKeyword_71_0; }

		//Medium_Slate_Blue
		public EnumLiteralDeclaration getMedium_Slate_BlueEnumLiteralDeclaration_72() { return cMedium_Slate_BlueEnumLiteralDeclaration_72; }

		//"Medium_Slate_Blue"
		public Keyword getMedium_Slate_BlueMedium_Slate_BlueKeyword_72_0() { return cMedium_Slate_BlueMedium_Slate_BlueKeyword_72_0; }

		//Medium_Spring_Green
		public EnumLiteralDeclaration getMedium_Spring_GreenEnumLiteralDeclaration_73() { return cMedium_Spring_GreenEnumLiteralDeclaration_73; }

		//"Medium_Spring_Green"
		public Keyword getMedium_Spring_GreenMedium_Spring_GreenKeyword_73_0() { return cMedium_Spring_GreenMedium_Spring_GreenKeyword_73_0; }

		//Medium_Turquoise
		public EnumLiteralDeclaration getMedium_TurquoiseEnumLiteralDeclaration_74() { return cMedium_TurquoiseEnumLiteralDeclaration_74; }

		//"Medium_Turquoise"
		public Keyword getMedium_TurquoiseMedium_TurquoiseKeyword_74_0() { return cMedium_TurquoiseMedium_TurquoiseKeyword_74_0; }

		//Medium_Violet_Red
		public EnumLiteralDeclaration getMedium_Violet_RedEnumLiteralDeclaration_75() { return cMedium_Violet_RedEnumLiteralDeclaration_75; }

		//"Medium_Violet_Red"
		public Keyword getMedium_Violet_RedMedium_Violet_RedKeyword_75_0() { return cMedium_Violet_RedMedium_Violet_RedKeyword_75_0; }

		//Medium_Wood
		public EnumLiteralDeclaration getMedium_WoodEnumLiteralDeclaration_76() { return cMedium_WoodEnumLiteralDeclaration_76; }

		//"Medium_Wood"
		public Keyword getMedium_WoodMedium_WoodKeyword_76_0() { return cMedium_WoodMedium_WoodKeyword_76_0; }

		//Midnight_Blue
		public EnumLiteralDeclaration getMidnight_BlueEnumLiteralDeclaration_77() { return cMidnight_BlueEnumLiteralDeclaration_77; }

		//"Midnight_Blue"
		public Keyword getMidnight_BlueMidnight_BlueKeyword_77_0() { return cMidnight_BlueMidnight_BlueKeyword_77_0; }

		//Navy_Blue
		public EnumLiteralDeclaration getNavy_BlueEnumLiteralDeclaration_78() { return cNavy_BlueEnumLiteralDeclaration_78; }

		//"Navy_Blue"
		public Keyword getNavy_BlueNavy_BlueKeyword_78_0() { return cNavy_BlueNavy_BlueKeyword_78_0; }

		//Neon_Blue
		public EnumLiteralDeclaration getNeon_BlueEnumLiteralDeclaration_79() { return cNeon_BlueEnumLiteralDeclaration_79; }

		//"Neon_Blue"
		public Keyword getNeon_BlueNeon_BlueKeyword_79_0() { return cNeon_BlueNeon_BlueKeyword_79_0; }

		//Neon_Pink
		public EnumLiteralDeclaration getNeon_PinkEnumLiteralDeclaration_80() { return cNeon_PinkEnumLiteralDeclaration_80; }

		//"Neon_Pink"
		public Keyword getNeon_PinkNeon_PinkKeyword_80_0() { return cNeon_PinkNeon_PinkKeyword_80_0; }

		//New_Midnight_Blue
		public EnumLiteralDeclaration getNew_Midnight_BlueEnumLiteralDeclaration_81() { return cNew_Midnight_BlueEnumLiteralDeclaration_81; }

		//"New_Midnight_Blue"
		public Keyword getNew_Midnight_BlueNew_Midnight_BlueKeyword_81_0() { return cNew_Midnight_BlueNew_Midnight_BlueKeyword_81_0; }

		//New_Tan
		public EnumLiteralDeclaration getNew_TanEnumLiteralDeclaration_82() { return cNew_TanEnumLiteralDeclaration_82; }

		//"New_Tan"
		public Keyword getNew_TanNew_TanKeyword_82_0() { return cNew_TanNew_TanKeyword_82_0; }

		//Old_Gold
		public EnumLiteralDeclaration getOld_GoldEnumLiteralDeclaration_83() { return cOld_GoldEnumLiteralDeclaration_83; }

		//"Old_Gold"
		public Keyword getOld_GoldOld_GoldKeyword_83_0() { return cOld_GoldOld_GoldKeyword_83_0; }

		//Orange_Red
		public EnumLiteralDeclaration getOrange_RedEnumLiteralDeclaration_84() { return cOrange_RedEnumLiteralDeclaration_84; }

		//"Orange_Red"
		public Keyword getOrange_RedOrange_RedKeyword_84_0() { return cOrange_RedOrange_RedKeyword_84_0; }

		//Orchid
		public EnumLiteralDeclaration getOrchidEnumLiteralDeclaration_85() { return cOrchidEnumLiteralDeclaration_85; }

		//"Orchid"
		public Keyword getOrchidOrchidKeyword_85_0() { return cOrchidOrchidKeyword_85_0; }

		//Pale_Green
		public EnumLiteralDeclaration getPale_GreenEnumLiteralDeclaration_86() { return cPale_GreenEnumLiteralDeclaration_86; }

		//"Pale_Green"
		public Keyword getPale_GreenPale_GreenKeyword_86_0() { return cPale_GreenPale_GreenKeyword_86_0; }

		//Plum
		public EnumLiteralDeclaration getPlumEnumLiteralDeclaration_87() { return cPlumEnumLiteralDeclaration_87; }

		//"Plum"
		public Keyword getPlumPlumKeyword_87_0() { return cPlumPlumKeyword_87_0; }

		//Quartz
		public EnumLiteralDeclaration getQuartzEnumLiteralDeclaration_88() { return cQuartzEnumLiteralDeclaration_88; }

		//"Quartz"
		public Keyword getQuartzQuartzKeyword_88_0() { return cQuartzQuartzKeyword_88_0; }

		//Rich_Blue
		public EnumLiteralDeclaration getRich_BlueEnumLiteralDeclaration_89() { return cRich_BlueEnumLiteralDeclaration_89; }

		//"Rich_Blue"
		public Keyword getRich_BlueRich_BlueKeyword_89_0() { return cRich_BlueRich_BlueKeyword_89_0; }

		//Scarlet
		public EnumLiteralDeclaration getScarletEnumLiteralDeclaration_90() { return cScarletEnumLiteralDeclaration_90; }

		//"Scarlet"
		public Keyword getScarletScarletKeyword_90_0() { return cScarletScarletKeyword_90_0; }

		//Sea_Green
		public EnumLiteralDeclaration getSea_GreenEnumLiteralDeclaration_91() { return cSea_GreenEnumLiteralDeclaration_91; }

		//"Sea_Green"
		public Keyword getSea_GreenSea_GreenKeyword_91_0() { return cSea_GreenSea_GreenKeyword_91_0; }

		//Semi_Sweet_Chocolate
		public EnumLiteralDeclaration getSemi_Sweet_ChocolateEnumLiteralDeclaration_92() { return cSemi_Sweet_ChocolateEnumLiteralDeclaration_92; }

		//"Semi_Sweet_Chocolate"
		public Keyword getSemi_Sweet_ChocolateSemi_Sweet_ChocolateKeyword_92_0() { return cSemi_Sweet_ChocolateSemi_Sweet_ChocolateKeyword_92_0; }

		//Sky_Blue
		public EnumLiteralDeclaration getSky_BlueEnumLiteralDeclaration_93() { return cSky_BlueEnumLiteralDeclaration_93; }

		//"Sky_Blue"
		public Keyword getSky_BlueSky_BlueKeyword_93_0() { return cSky_BlueSky_BlueKeyword_93_0; }

		//Slate_Blue
		public EnumLiteralDeclaration getSlate_BlueEnumLiteralDeclaration_94() { return cSlate_BlueEnumLiteralDeclaration_94; }

		//"Slate_Blue"
		public Keyword getSlate_BlueSlate_BlueKeyword_94_0() { return cSlate_BlueSlate_BlueKeyword_94_0; }

		//Spicy_Pink
		public EnumLiteralDeclaration getSpicy_PinkEnumLiteralDeclaration_95() { return cSpicy_PinkEnumLiteralDeclaration_95; }

		//"Spicy_Pink"
		public Keyword getSpicy_PinkSpicy_PinkKeyword_95_0() { return cSpicy_PinkSpicy_PinkKeyword_95_0; }

		//Spring_Green
		public EnumLiteralDeclaration getSpring_GreenEnumLiteralDeclaration_96() { return cSpring_GreenEnumLiteralDeclaration_96; }

		//"Spring_Green"
		public Keyword getSpring_GreenSpring_GreenKeyword_96_0() { return cSpring_GreenSpring_GreenKeyword_96_0; }

		//// "Steel Blue"
		//Steel_Blue
		public EnumLiteralDeclaration getSteel_BlueEnumLiteralDeclaration_97() { return cSteel_BlueEnumLiteralDeclaration_97; }

		//"Steel_Blue"
		public Keyword getSteel_BlueSteel_BlueKeyword_97_0() { return cSteel_BlueSteel_BlueKeyword_97_0; }
	}
	
	private FMFUIElements pFMFUI;
	private FiducialElements pFiducial;
	private FMFSettingsElements pFMFSettings;
	private FMFProximaVisibleEnumElements unknownRuleFMFProximaVisibleEnum;
	private FMFFidStyleEnumElements unknownRuleFMFFidStyleEnum;
	private FMFKindElements unknownRuleFMFKind;
	private FMFFidFunctionEnumElements unknownRuleFMFFidFunctionEnum;
	private FMFFidKindElements unknownRuleFMFFidKind;
	private FMFFidColorEnumElements unknownRuleFMFFidColorEnum;
	
	private final GrammarProvider grammarProvider;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public FmurfUiDSLGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammarProvider = grammarProvider;
		this.gaTerminals = gaTerminals;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//FMFUI:
	//	settings=FMFSettings fiducials+=Fiducial*;
	public FMFUIElements getFMFUIAccess() {
		return (pFMFUI != null) ? pFMFUI : (pFMFUI = new FMFUIElements());
	}
	
	public ParserRule getFMFUIRule() {
		return getFMFUIAccess().getRule();
	}

	//Fiducial:
	//	"fiducial" name=ID ":" uid=INT "{" "style:" style=FMFFidStyleEnum "kind:" kind=FMFKind "foreground:"
	//	fg=FMFFidColorEnum "background:" bg=FMFFidColorEnum "radius:" radius=INT "proxima:" proxima=INT "proximaVisible:"
	//	proximaVisible=FMFProximaVisibleEnum "function:" function=FMFFidFunctionEnum "range:" range=INT "}";
	public FiducialElements getFiducialAccess() {
		return (pFiducial != null) ? pFiducial : (pFiducial = new FiducialElements());
	}
	
	public ParserRule getFiducialRule() {
		return getFiducialAccess().getRule();
	}

	//FMFSettings:
	//	"settings : {" "OscReceivePort:" oscReceivePort=INT "OscSendAddress:" oscSendAddress=STRING "OscSendPort:"
	//	oscSendPort=INT "TuioPort:" tuioPort=INT "liveRate:" liveRate=INT "processingRate:" processingRate=INT "}";
	public FMFSettingsElements getFMFSettingsAccess() {
		return (pFMFSettings != null) ? pFMFSettings : (pFMFSettings = new FMFSettingsElements());
	}
	
	public ParserRule getFMFSettingsRule() {
		return getFMFSettingsAccess().getRule();
	}

	//enum FMFProximaVisibleEnum:
	//	VISIBLE | HIDDEN;
	public FMFProximaVisibleEnumElements getFMFProximaVisibleEnumAccess() {
		return (unknownRuleFMFProximaVisibleEnum != null) ? unknownRuleFMFProximaVisibleEnum : (unknownRuleFMFProximaVisibleEnum = new FMFProximaVisibleEnumElements());
	}
	
	public EnumRule getFMFProximaVisibleEnumRule() {
		return getFMFProximaVisibleEnumAccess().getRule();
	}

	//enum FMFFidStyleEnum:
	//	DISC | SQUARE | PENTAGON | HEXAGON | EIGHTSTAR;
	public FMFFidStyleEnumElements getFMFFidStyleEnumAccess() {
		return (unknownRuleFMFFidStyleEnum != null) ? unknownRuleFMFFidStyleEnum : (unknownRuleFMFFidStyleEnum = new FMFFidStyleEnumElements());
	}
	
	public EnumRule getFMFFidStyleEnumRule() {
		return getFMFFidStyleEnumAccess().getRule();
	}

	//enum FMFKind:
	//	SIN_OSC | SQR_OSC | PULSE_OSC | TRI_OSC | SAW_OSC | SEQUENCER | SAMPLER | ECHO | REVERB;
	public FMFKindElements getFMFKindAccess() {
		return (unknownRuleFMFKind != null) ? unknownRuleFMFKind : (unknownRuleFMFKind = new FMFKindElements());
	}
	
	public EnumRule getFMFKindRule() {
		return getFMFKindAccess().getRule();
	}

	//enum FMFFidFunctionEnum:
	//	KNOB | NONE;
	public FMFFidFunctionEnumElements getFMFFidFunctionEnumAccess() {
		return (unknownRuleFMFFidFunctionEnum != null) ? unknownRuleFMFFidFunctionEnum : (unknownRuleFMFFidFunctionEnum = new FMFFidFunctionEnumElements());
	}
	
	public EnumRule getFMFFidFunctionEnumRule() {
		return getFMFFidFunctionEnumAccess().getRule();
	}

	//enum FMFFidKind:
	//	SinOsc | SqrOsc | TriOsc | SawOsc | PulseOsc | Phasor | Sequencer | Sampler | Reverb | Echo;
	public FMFFidKindElements getFMFFidKindAccess() {
		return (unknownRuleFMFFidKind != null) ? unknownRuleFMFFidKind : (unknownRuleFMFFidKind = new FMFFidKindElements());
	}
	
	public EnumRule getFMFFidKindRule() {
		return getFMFFidKindAccess().getRule();
	}

	//enum FMFFidColorEnum:
	//	Aquamarine // "Aquamarine"
	//	// "Baker's Chocolate"
	//	// "Black"
	//	// "Blue"
	//	// "Brass"
	//	// "Bright Gold"
	//	// "Brown"
	//	// "Bronze"
	//	// "Gold"
	//	// "Grey"
	//	// "Green"
	//	// "Copper"
	//	// "Coral"
	//	// "Cyan"
	//	// "Dark Green"
	//	// "Green Yellow"
	//	// "Magenta"
	//	// "Maroon"
	//	// "Medium Blue"
	//	// "Sienna"
	//	// "Silver"
	//	// "Salmon"
	//	// "Orange"
	//	// "Pink"
	//	// "Red"
	//	// "Summer Sky"
	//	// "Tan"
	//	// "Thistle"
	//	// "Turquoise"
	//	// "Very Dark Brown"
	//	// "Very Light Grey"
	//	// "Violet"
	//	// "Violet Red"
	//	// "Wheat"
	//	// "White"
	//	// "Yellow"
	//	// "Yellow Green"
	//	// "Dark Yellow"
	//	// "Bronze II"
	//	// "Cadet Blue"
	//	// "Cool Copper"
	//	// "Corn Flower Blue"
	//	// "Dark Brown"
	//	// "Dark Green Copper"
	//	// "Dark Olive Green"
	//	// "Dark Orchid"
	//	// "Dark Purple"
	//	// "Dark Slate Blue"
	//	// "Dark Turquoise"
	//	// "Dark Tan"
	//	// "Dark Wood"
	//	// "Dim Grey"
	//	// "Dusty Rose"
	//	// "Feldspar"
	//	// "Firebrick"
	//	// "Forest Green"
	//	// "Goldenrod"
	//	// "Green Copper"
	//	// "Hunter Green"
	//	// "Indian Red"
	//	// "Khaki"
	//	// "Light Blue"
	//	// "Light Grey"
	//	// "Light Steel Blue"
	//	// "Light Wood"
	//	// "Lime Green"
	//	// "Mandarian Orange"
	//	// "Medium Aquamarine"
	//	// "Medium Forest Green"
	//	// "Medium Goldenrod"
	//	// "Medium Orchid"
	//	// "Medium Sea Green"
	//	// "Medium Slate Blue"
	//	// "Medium Spring Green"
	//	// "Medium Turquoise"
	//	// "Medium Violet Red"
	//	// "Medium Wood"
	//	// "Midnight Blue"
	//	// "Navy Blue"
	//	// "Neon Blue"
	//	// "Neon Pink"
	//	// "New Midnight Blue"
	//	// ""
	//	// "Old Gold"
	//	// "Orange Red"
	//	// "Orchid"
	//	// "Pale Green"
	//	// "Plum"
	//	// "Quartz"
	//	// "Rich Blue"
	//	// "Scarlet"
	//	// "Sea Green"
	//	// "Semi-Sweet Chocolate"
	//	// "Sky Blue"
	//	// "Slate Blue"
	//	// "Spicy Pink"
	//	// "Spring Green"
	//	| Bakers_Chocolate | Black | Blue | Brass | Bright_Gold | Brown | Bronze | Gold | Grey | Green | Copper | Coral | Cyan
	//	| Dark_Green | Green_Yellow | Magenta | Maroon | Medium_Blue | Sienna | Silver | Salmon | Orange | Pink | Red |
	//	Summer_Sky | Tan | Thistle | Turquoise | Very_Dark_Brown | Very_Light_Grey | Violet | Violet_Red | Wheat | White |
	//	Yellow | Yellow_Green | Dark_Yellow | Bronze_II | Cadet_Blue | Cool_Copper | Corn_Flower_Blue | Dark_Brown |
	//	Dark_Green_Copper | Dark_Olive_Green | Dark_Orchid | Dark_Purple | Dark_Slate_Blue | Dark_Turquoise | Dark_Tan |
	//	Dark_Wood | Dim_Grey | Dusty_Rose | Feldspar | Firebrick | Forest_Green | Goldenrod | Green_Copper | Hunter_Green |
	//	Indian_Red | Khaki | Light_Blue | Light_Grey | Light_Steel_Blue | Light_Wood | Lime_Green | Mandarian_Orange |
	//	Medium_Aquamarine | Medium_Forest_Green | Medium_Goldenrod | Medium_Orchid | Medium_Sea_Green | Medium_Slate_Blue |
	//	Medium_Spring_Green | Medium_Turquoise | Medium_Violet_Red | Medium_Wood | Midnight_Blue | Navy_Blue | Neon_Blue |
	//	Neon_Pink | New_Midnight_Blue | New_Tan | Old_Gold | Orange_Red | Orchid | Pale_Green | Plum | Quartz | Rich_Blue |
	//	Scarlet | Sea_Green | Semi_Sweet_Chocolate | Sky_Blue | Slate_Blue | Spicy_Pink | Spring_Green | // "Steel Blue"
	//	Steel_Blue;
	public FMFFidColorEnumElements getFMFFidColorEnumAccess() {
		return (unknownRuleFMFFidColorEnum != null) ? unknownRuleFMFFidColorEnum : (unknownRuleFMFFidColorEnum = new FMFFidColorEnumElements());
	}
	
	public EnumRule getFMFFidColorEnumRule() {
		return getFMFFidColorEnumAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" | "n" |
	//	"f" | "r" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
